### ISSUE TITLE
Mixtral example is giving non-sensical output

### ISSUE THREAD

**Issue by samikama** [ml-explore/mlx-examples#100]
It seems that mixtral example is giving non-sensical output when used with non-default arguments. Is this expected?
Here is an example
```
python mixtral.py --model_path ../../mixtral/ -m 2000 --prompt "keep continuing the following story. In the beginning the Universe was created."
[INFO] Loading model from disk.
[INFO] Starting generation...
keep continuing the following story. In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move"""
import random


def test(actual, expected):
    """
      >>> test(10, 10)
      True
    """
    if actual == expected:
        return True
    else:
        return False


def secret(a=1, b=3, c=6, d=12):
    x, y, z, w = a, b, c, d
    a, b, c, d = my_secret(a, b, c, d, y)
    b, y = my_Formatting(a, b, c, d, y)
    x, z = my_XOR(a, b, c, d, x, y, z, w)
    z, w = my_SecretNa(x, z, w)
    y, z, w = my_Formatting(x, y, z, w)
    w, x, y, z = my_XOR(x, y, z, w, x, y, z, w)
    y, z, w = my_Formatting(x, y, z, w)
    w, x, y, z = my_XOR(x, y, z, w, x, y, z, w)
    y, z, w = my_Formatting(x, y, z, w)
    w, x, y, z = my_XOR(x, y, z, w, x, y, z, w)
    b, c = my_NewSecret(x, y, z, w, b, c)
    w, z, x, y = my_NewInfo(a, b, c, d, w, z, x, y)
    b, y, z, x = my_NewChoice(a, b, c, d, b, y, z, x)
    task = my_NextTask(b, y, z, x, task)

    return task


def my_secret(a, b, c, d, x):
    a, b, c, d = 3, 2, 5, 4
    x, y, z, w = 100, 300, 500, 800
    b, y, z, x = 200, 100, 120, 1600

    return x


def my_Formatting(a, b, c, d, x):
    a, b, c, d = 3, 2, 5, 4
    x, y, z, w = 100, 300, 500, 800
    b, y, z, x = 200, 100, 120, 1600

    return x


def my_XOR(a, b, c, d, x, y, z, w):
    a, b, c, d = 3, 2, 5, 4
    x, y, z, w = 100, 300, 500, 800
    b, y, z, x = 200, 100, 120, 1600

    return x


def my_secret2(a, b, c, d, x):
    a, b, c, d = 3, 2, 5, 4
    x, y, z, w = 100, 300, 500, 800
    b, y, z, x = 200, 100, 120, 1600

    return x


def my_NewSecret(a, b, c, d, x):
    a, b, c, d = 3, 2, 5, 4
    x, y, z, w = 100, 300, 500, 800
    b, y, z, x = 200, 100, 120, 1600

    return x


def my_NextTask(a, b, c, d, x):
    a, b, c, d = 3, 2, 5, 4
    x, y, z, w = 100, 300, 500, 800
    b, y, z, x = 200, 100, 120, 1600

    return x


def main():
    print ("starting the following code from the beginning")

    for random.choice('secret'):

        while random.loop()

            when random.choice ('secret2') and random.loop():

                if random.loop() and random.loop():

                    break

                else:

                    continue

        elif random.loop() and random.loop():

            break

        else:

            continue


# for _ in range(10):
#     secret()
#     secret()

# secret()
# if __name__ == "__main__":
#     main()

# check if it gives a different result.
test(1, 1)
# print ("okay long buddy.")
# print ("WOW YOU FOOLED ME!")
# # print ("here is a frog that doesn't like to be exposed to direct sunlight.") ц񋀀  񋀀并并并并并起适不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不不但不但不但不但不但不但不但不但不但不但不但不但不但不但不但不但不但不但不但不都不\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
```

**Comment by samikama** [comment]
Thanks. 
May be default prompt should be updated then.  The current default is
```
parser.add_argument(
        "--prompt",
        help="The message to be processed by the model",
        default="In the beginning the Universe was created.",
    )
```
That is the reason I  passed that argument.

**Comment by samikama** [comment]
Well, I tried 2 more versions based on your suggestions,
`python mixtral.py --model_path ../../mixtral/ -m 2000 --prompt " [INST] keep continuing the following story. In the beginning the Universe was created. [/INST] "` and 
` python mixtral.py --model_path ../../mixtral/ -m 2000 --prompt " [INST] {keep continuing the following story. In the beginning the Universe was created.} [/INST] "`
Both are similar outcomes
```
python mixtral.py --model_path ../../mixtral/ -m 2000 --prompt " [INST] {keep continuing the following story. In the beginning the Universe was created.} [/INST] "
[INFO] Loading model from disk.
[INFO] Starting generation...
 [INST] {keep continuing the following story. In the beginning the Universe was created.} [/INST]  [INST] {
For a long time I have wanted to create a detailed, scientific model of the Universe, that would be based on very few assumptions, but that would also explain all known astronomical parameters and observations in as much detail as possible. } [/INST]  <hr>Quote: Savan: I rushed home after work yesterday with the threat of vacation hanging over me, and wrote up a nice description of the background and purpose of the model. But when it came time to save, it crapped out all over my shoes. All I have managed to keep on record is a very short and incomplete description of the background, purpose, and details of the model. Below is all I have managed to save, and I am not sure how much of this is actually useful. What I would actually like to present is the piece of writing that I finished yesterday, but all my attempts to save it have failed. My computer crashed on me during an import procedure involved with an attempt to save the document to my computer's hard drive:
Quote: I have to import a Peek 7.0 Preference file before I try to save the "Crosstalk" thing again next time. Please wait while I finish this import procedure. I wonder what the Peek 7.0 Preference file looks like. I have to import a Peek 7.0 Preference file in order to save the "Crosstalk" thing again next time. Please wait while I finish this import procedure. I wonder what the Peek 7.0 Preference file looks like. I want it! I want it! It wants me! It wants me! I hate it! I hate it! It hates me! It hates me! It conflicts with me! It conflicts with me! There is insufficient system memory to perform this import procedure. There is a system disk error that is causing this import procedure to fail. The disk that was attached to this computer's floppy disk drive interfaced disk controller read interface has timed out because it cannot read any data from the disk quickly enough (because the disk access speeds are too slow) in order to satisfy the minimum manufacturer's specified recommended optimal mandatory minimum safe minimum practical realistically acceptable minimum effective minimum dimensionally satisfactory dimensionally appropriate realistically acceptable nominal minimum effective dimensionally satisfactory dimensionally appropriate realistically acceptable nominal minimum volumes amounts quantities numbers at positions latitudes longitudes altitudes curtain heights during curtain hours particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly peculiarly particularly pecularly peculiarly particularly peculiar particular peculiarly peculiarly particularly peculiarly peculiarly peculiarly peculiarly peculiarly peculiarly peculiarly peculiarily peculiarily peculiarly peculiariest peculiarly peculiaryest peculiarly peculiaryest peculiarly peculiarly peculiaryest peculiarly peculiarly peculiaryest peculiarly peculiaryest peculiarly peculiaryest peculiarly peculiaryest peculiarly peculiaryest peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiary est peculiariest partially particularly peculiary peculiary peculiary peculiary particularly particularly particularly particularly particularly particularly particularly particularly particularly particularly peculiary peculiary peculiary peculiary peculiary peculiary peculiary peculiary peculiary peculiary peculiary peculiary peculiary peculiary peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest pecul peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest peculiariest pecul_

_: 7/30/03:_: 7/31/03:_: 7/1/03: 4 1/2 2/3 1/4 2/10 3/12 1/5 2/14 9/5 3/10 1/3 8/5 14/6 3/12 27/6 13/11 16/3 18/4 126/43 1/3 2/3 1/2 1/3 1/4 1/6 2/9 1/9 2/11 3/13 4/13 1/26 1/26 1/26 1/26 1/26 1/26 1/14 1/21 1/21 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/21 1/21 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/42 1/6 6/6 4/2 12/2 6/3 4/5 5/2 2/3 3/5 4/11 7/12 1/2 5/4 10/4 15/2 25/2 40/3 72/6 127/2 271/3 211/21 12496/6185 31583
```

**Comment by awni** [comment]
Are you using the Instruct version or the regular version? For the regular model you shouldn't need such a specific prompt format.  Actually it looks like using a `--temp=0.0` gives better results with that model. The temperature might need to be tuned or we may need to have a different sampling method. It is also possible there is a bug in the generation. Let me know if you have any luck tuning the temp, I will start hunting for bugs.

**Comment by justinh-rahb** [comment]
@samikama Remove the { } brackets, I copied that from Ollama's modelfile for Mixtral and it's an artifact of the templating system. My experience is only with the instruct-tuned version, I have not been using the base version. I've also found lower temperature to produce better results in the instruct model @awni

**Comment by samikama** [comment]
@justinh-rahb Thanks, As I mentioned I tried both. I tried without braces first actually. I just pasted last attempt to keep the message smaller. Both are similarly non-sensical

@awni Thanks for the response. I followed the instructions on the ReadMe file. Merged model file md5 hash matches the one in the documentation. I can't tune the temp right now since it looks like a recent change broke the mixtral.
```
python mixtral.py --model_path ../../mixtral/ -m 2000 --prompt " [INST] {keep continuing the following story. In the beginning the Universe was created.} [/INST] "
[INFO] Loading model from disk.
Traceback (most recent call last):
  File "/Users/sami/C-Gen/Experiments/mlx-examples/mixtral/mixtral.py", line 289, in <module>
    model, tokenizer = load_model(args.model_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sami/C-Gen/Experiments/mlx-examples/mixtral/mixtral.py", line 233, in load_model
    weights = tree_unflatten(list(weights.items()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sami/C-Gen/Experiments/MLX/lib/python3.12/site-packages/mlx/utils.py", line 115, in tree_unflatten
    int(tree[0][0].split(".", maxsplit=1)[0])
        ~~~~^^^
IndexError: list index out of range
$ git log --oneline
a3ecda2 (HEAD -> main, origin/main, origin/HEAD) Merge pull request #107 from ml-explore/hf_mixtral
b863e7c (origin/hf_mixtral) format

```

**Comment by justinh-rahb** [comment]
I know the llama.cpp folks spent a few days playing with things before they got results they considered to be bug-free enough to merge the feature into main, so it's possible there's issues with the inference code here.

**Comment by lostmygithubaccount** [comment]
I still saw similar w/ llama.cpp recently -- planning to test Mixtral (base and instruct) on both more in the next couple weeks, will report on any relevant findings

**Comment by awni** [comment]
I pushed a fix + minor changes to #112 and will merge soon. 

The outputs are much better for me now. Let me know how they look for you if you have a chance to test it.

**Comment by awni** [comment]
Comment here if you are still seeing issues after updating the example and I will reopen.

**Comment by samikama** [comment]
Thanks. I fetched the updates to repo, downloaded the new base model in README but it looks like it did not change much. First few tokens seems reasonable but it fails shortly after. Even with the default prompt
```
python mixtral.py --model_path ../../mixtral-8x7B-v0.1/ -m 500
[INFO] Loading model from disk.
[INFO] Starting generation...
In the beginning the Universe was created. This has made a lot of people very angry and been widely

regarded as a bad move.

Douglus Adams

The Hitchhiker’s Guide to the Universe

The Universe is a very big place. It is so big that it is hard to comprehend. It is so big that it is hard to comprehend how big it is.

The Universe is so big that it is hard to comprehend how big it is.

The Universe is so big that it is hard to comprehend how big it is.

The Universe is so big that it is hard to comprehend how big it is.

The Universe is so big that it is hard to comprehend how big it is.

The Universe is^CTraceback (most recent call last):
  File "/Users/sami/C-Gen/Experiments/mlx-examples/mixtral/mixtra....
```

**Comment by lostmygithubaccount** [comment]
I believe you need to change how you're prompting it, see https://github.com/ggerganov/llama.cpp/pull/4406#issuecomment-1853523039 and other pointers in that thread (and the instructions in the huggingface repo) -- reportedly temperature=0 also helps 

perhaps the default example prompt should also be updated?

**Comment by awni** [comment]
The default temp is now `0.0`. @samikama interesting. I get similar results to you with the default prompt. When I try the prompt you originally provided though it looks pretty nice:

```
python mixtral.py --model_path ~/models/Mixtral-8x7B-v0.1 -m 200 --prompt "keep continuing the following story. In the beginning the Universe was created." --temp 0.0 
```

```
keep continuing the following story. In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.

Douglas Adams

The Hitchhiker’s Guide to the Galaxy

The Hitchhiker’s Guide to the Galaxy is a comedy science fiction series created by Douglas Adams. Originally a radio comedy broadcast on BBC Radio 4 in 1978, it was later adapted to other formats, including stage shows, novels, comic books, a 1981 TV series, a 1984 computer game, and 2005 feature film.

The series follows the adventures of hapless Englishman Arthur Dent, who is rescued from Earth moments before it is destroyed to make way for a hyperspace bypass. He travels through the galaxy with his friend Ford Prefect, a human-like alien (and researcher for the eponymous guidebook) who was stranded on Earth five
```

**Comment by samikama** [comment]
It is weird. For me 
``` python mixtral.py --model_path ../../mixtral-8x7B-v0.1 -m 200 --prompt "keep continuing the following story. In the beginning the Universe was created." --temp 0.0
[INFO] Loading model from disk.
[INFO] Starting generation...
keep continuing the following story. In the beginning the Universe was created. This has made a lot of people very angry and been widely

regarded as a bad move.

Doug Adams

The Universe is a big place, perhaps the biggest.

Carl Sagan

The Universe is a big place, perhaps the biggest.

Carl Sagan

The Universe is a big place, perhaps the biggest.

Carl Sagan
```
I am using python 3.12 and consequently PT nightly since there is no py-3.12 builds for Mac for release versions. Perhaps nightly is buggy.

**Comment by awni** [comment]
Python version shouldn’t matter… maybe try updating mlx:

‘pip install -U mlx’

**Comment by samikama** [comment]
According to pip, it is most recent version  `(0.0.5)` I just updated the torch to 20231215. Didn't change anything.

**Comment by awni** [comment]
Hmm we should be getting the same results with a temperature of 0.0. Could you verify you are using the latest mlx-examples? The file `mixtral/mixtral.py` should have the custom RoPE class in it l[ike this](https://github.com/ml-explore/mlx-examples/blob/main/mixtral/mixtral.py#L44-L61).

**Comment by samikama** [comment]
Yes it is the same. I am at `main`,  commit `08e862336ade809bc37d1`
