### ISSUE TITLE
mlx_lm.convert fails in the absence of a config.json file

### ISSUE THREAD

**Issue by jrp2014** [ml-explore/mlx-examples#1033]
Downloading a model using the hugging face cli and then trying to convert it doesn't seem to work:
```
python -m mlx_lm.convert --hf-path mistralai/Pixtral-12B-2409
[INFO] Loading
Fetching 3 files: 100%|████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 49344.75it/s]
ERROR:root:Config file not found in /Users/xxx/.cache/huggingface/hub/models--mistralai--Pixtral-12B-2409/snapshots/df119bf36c0cedc6ffdc9ca6c58ebf51f9771ef7
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_lm/convert.py", line 62, in <module>
    main()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_lm/convert.py", line 58, in main
    convert(**vars(args))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_lm/utils.py", line 718, in convert
    model, config, tokenizer = fetch_from_hub(model_path, lazy=True)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_lm/utils.py", line 502, in fetch_from_hub
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_lm/utils.py", line 413, in load_model
    config = load_config(model_path)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_lm/utils.py", line 377, in load_config
    with open(model_path / "config.json", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/.cache/huggingface/hub/models--mistralai--Pixtral-12B-2409/snapshots/df119bf36c0cedc6ffdc9ca6c58ebf51f9771ef7/config.json'
```
The snapshot directory contains:

```
README.md                consolidated.safetensors params.json              tekken.json
```

**Comment by awni** [comment]
Yes two problems here:
1. MLX LM only converts Hugging Face / Transformers format models which must have a `config.json`. So you should use this one instead: `mlx-community/pixtral-12b-bf16`.
2. MLX LM does not currently support multi model inputs. For that I suggest you check-out [MLX VLM](https://github.com/Blaizzy/mlx-vlm)
