### ISSUE TITLE
[mlx-whisper] Error while transcribing - Cannot infer the shape of an empty array

### ISSUE THREAD

**Issue by thelazyoxymoron** [ml-explore/mlx-examples#1084]
System: M1 Max
MLX: `0.4.0` (from PyPi)

When transcribing a video, sometimes it fails with the following error:

```
Traceback (most recent call last):
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/cli.py", line 224, in main
    result = transcribe(
             ^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/transcribe.py", line 295, in transcribe
    result: DecodingResult = decode_with_fallback(mel_segment)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/transcribe.py", line 222, in decode_with_fallback
    decode_result = model.decode(segment, options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/decoding.py", line 742, in decode
    result = DecodingTask(model, options).run(mel)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/decoding.py", line 652, in run
    tokens, sum_logprobs, no_speech_probs = self._main_loop(audio_features, tokens)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/decoding.py", line 605, in _main_loop
    next_tokens, next_completed, next_sum_logprobs, _ = _step(
                                                        ^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/decoding.py", line 577, in _step
    pre_logits = self.inference.logits(inputs, audio_features)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/decoding.py", line 139, in logits
    logits, self.kv_cache, _ = self.model.decoder(
                               ^^^^^^^^^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/whisper.py", line 193, in __call__
    x, kv_cache[e], cross_qk[e] = block(
                                  ^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/whisper.py", line 109, in __call__
    y, kv, _ = self.attn(self.attn_ln(x), mask=mask, kv_cache=kv)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/whisper.py", line 70, in __call__
    wv, qk = self.qkv_attention(q, k, v, mask)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carteblanche/Projects/playground/machine-learning/mlx-whisper/.venv/lib/python3.12/site-packages/mlx_whisper/whisper.py", line 76, in qkv_attention
    q = q.reshape(*q.shape[:2], self.n_head, -1).transpose(0, 2, 1, 3) * scale
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [reshape] Cannot infer the shape of an empty array
Skipping Le date avec un New yorkais qui a changé ma vie [cIYjKSo9G5w].webm due to ValueError: [reshape] Cannot infer the shape of an empty array
```

Tried with [this video](https://www.youtube.com/watch?v=cIYjKSo9G5w)

**Comment by qnguyen3** [comment]
same i got the same :(

**Comment by awni** [comment]
Yes the fix is here just waiting to get it released

**Comment by awni** [comment]
The patch release is on pypi you can `pip install -U mlx-whisper` and it should work now.
