### ISSUE TITLE
ValueError: The number of image tokens (576) does not  match the number of image inputs (1).

### ISSUE THREAD

**Issue by agent-clement** [ml-explore/mlx-examples#1138]
When running the Llava example:

`python generate.py \
  --model llava-hf/llava-1.5-7b-hf \
  --image "http://images.cocodataset.org/val2017/000000039769.jpg" \
  --prompt "USER: <image>\nWhat are these?\nASSISTANT:" \
  --max-tokens 128 \
  --temp 0`

The script returns an error:

`Traceback (most recent call last):
  File "mlx-examples/llava/generate.py", line 140, in <module>
    main()
  File "mlx-examples/llava/generate.py", line 133, in main
    generated_text = generate_text(
                     ^^^^^^^^^^^^^^
  File "mlx-examples/llava/generate.py", line 102, in generate_text
    logits, cache = model(input_ids, pixel_values)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlx-examples/llava/llava.py", line 137, in __call__
    input_embddings = self.get_input_embeddings(input_ids, pixel_values)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlx-examples/llava/llava.py", line 98, in get_input_embeddings
    final_inputs_embeds = self._merge_input_ids_with_image_features(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlx-examples/llava/llava.py", line 116, in _merge_input_ids_with_image_features
    raise ValueError(
ValueError: The number of image tokens (576) does not  match the number of image inputs (1).`

`test.py` fails the same way. How do I make it work? Thanks so much!

**Comment by awni** [comment]
This is fixed if you pull the latest mlx-examples.
