### ISSUE TITLE
phi2/convert.py: requires flash_attn

### ISSUE THREAD

**Issue by bruse** [ml-explore/mlx-examples#114]
When running
> % pip install -r requirements.txt
> ...
> % python convert.py
> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "convert.py", line 24, in <module>
    convert()
  File "convert.py", line 15, in convert
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 440, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 373, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 247, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 141, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

`pip install flash_attn` fails because of cuda requirements (nvcc is required), but as far as I can tell there is not support for nvcc on MacOS. Is this expected on the AArch64 Macs?

**Comment by awni** [comment]
Is this for the Phi2 example? I did not need to install `flash_attn` for that, that is very strange...

**Comment by bruse** [comment]
Yes, sorry I should have been more clear in the body. I just put it in the title.

**Comment by awni** [comment]
Maybe it's a `transformers` version problem. Can you do (in your phi2 env):

```
pip list | grep transformers
```

**Comment by bruse** [comment]
> transformers            4.18.0

**Comment by bruse** [comment]
`pip install --upgrade transformers` did indeed fix it. Thank you, and sorry for my poor environment.
