### ISSUE TITLE
cannot use lora with t5 models

### ISSUE THREAD

**Issue by demhademha** [ml-explore/mlx-examples#1160]
download this repository and run: 

```


 

python3 convert.py  --hf-path google-t5/t5-small -q 
/Users/ahmedhassan/Library/Python/3.9/lib/python/site-packages/urllib3/init.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[INFO] Loading
Fetching 5 files: 100%|████████████████████████| 5/5 [00:00<00:00, 63167.23it/s]
[INFO] Quantizing
Traceback (most recent call last):
  File "/Users/ahmedhassan/Documents/ai2/lora/convert.py", line 93, in <module>
    weights, config = quantize(weights, config, args)
  File "/Users/ahmedhassan/Documents/ai2/lora/convert.py", line 17, in quantize
    model = models.Model(models.ModelArgs.from_dict(config))
  File "/Users/ahmedhassan/Documents/ai2/lora/models.py", line 40, in from_dict
    return cls(
TypeError: init() missing 5 required positional arguments: 'hidden_size', 'num_hidden_layers', 'intermediate_size', 'num_attention_heads', and 'rms_norm_eps'

```

python version: 3.9.6 
MacOS version: 15.2 
note this also effects t5-base as well as the flan-t5 models

**Comment by awni** [comment]
Indeed, T5 is not supported with that example. We don't plan to add it there as that example is intended to be minimal and only supports llama-style models. Your best bet is to modify the example to use our [T5 implementation](https://github.com/ml-explore/mlx-examples/tree/main/t5) instead
