### ISSUE TITLE
Cannot use lora with gemma

### ISSUE THREAD

**Issue by demhademha** [ml-explore/mlx-examples#1161]
```

python3 convert.py --hf-path google/gemma-2-2b-it -q
/Users/ahmedhassan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[INFO] Loading
Fetching 9 files: 100%|████████████████████████| 9/9 [00:00<00:00, 35578.45it/s]
[INFO] Quantizing
Traceback (most recent call last):
  File "/Users/ahmedhassan/Github/mlx-examples/lora/convert.py", line 93, in <module>
    weights, config = quantize(weights, config, args)
  File "/Users/ahmedhassan/Github/mlx-examples/lora/convert.py", line 18, in quantize
    model.load_weights(list(weights.items()))
  File "/Users/ahmedhassan/Library/Python/3.9/lib/python/site-packages/mlx/nn/layers/base.py", line 178, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.20.pre_feedforward_layernorm.weight model.layers.14.pre_feedforward_layernorm.weight model.layers.12.pre_feedforward_layernorm.weight model.layers.22.post_feedforward_layernorm.weight model.layers.24.post_feedforward_layernorm.weight model.layers.8.pre_feedforward_layernorm.weight model.layers.6.post_feedforward_layernorm.weight model.layers.25.pre_feedforward_layernorm.weight model.layers.0.post_feedforward_layernorm.weight model.layers.23.pre_feedforward_layernorm.weight model.layers.7.post_feedforward_layernorm.weight model.layers.4.post_feedforward_layernorm.weight model.layers.2.post_feedforward_layernorm.weight model.layers.15.pre_feedforward_layernorm.weight model.layers.9.post_feedforward_layernorm.weight model.layers.9.pre_feedforward_layernorm.weight model.layers.19.pre_feedforward_layernorm.weight model.layers.3.pre_feedforward_layernorm.weight model.layers.21.pre_feedforward_layernorm.weight model.layers.11.pre_feedforward_layernorm.weight model.layers.6.pre_feedforward_layernorm.weight model.layers.21.post_feedforward_layernorm.weight model.layers.16.post_feedforward_layernorm.weight model.layers.23.post_feedforward_layernorm.weight model.layers.22.pre_feedforward_layernorm.weight model.layers.18.post_feedforward_layernorm.weight model.layers.20.post_feedforward_layernorm.weight model.layers.1.post_feedforward_layernorm.weight model.layers.13.post_feedforward_layernorm.weight model.layers.2.pre_feedforward_layernorm.weight model.layers.10.post_feedforward_layernorm.weight model.layers.25.post_feedforward_layernorm.weight model.layers.24.pre_feedforward_layernorm.weight model.layers.16.pre_feedforward_layernorm.weight model.layers.11.post_feedforward_layernorm.weight model.layers.15.post_feedforward_layernorm.weight model.layers.18.pre_feedforward_layernorm.weight model.layers.4.pre_feedforward_layernorm.weight model.layers.5.pre_feedforward_layernorm.weight model.layers.13.pre_feedforward_layernorm.weight model.layers.8.post_feedforward_layernorm.weight model.layers.7.pre_feedforward_layernorm.weight model.layers.12.post_feedforward_layernorm.weight model.layers.0.pre_feedforward_layernorm.weight model.layers.3.post_feedforward_layernorm.weight model.layers.5.post_feedforward_layernorm.weight model.layers.1.pre_feedforward_layernorm.weight model.layers.17.pre_feedforward_layernorm.weight model.layers.14.post_feedforward_layernorm.weight model.layers.10.pre_feedforward_layernorm.weight model.layers.17.post_feedforward_layernorm.weight model.layers.19.post_feedforward_layernorm.weight.

```

python version: 3.9.6 
product version: 15.2

**Comment by awni** [comment]
You'd need to use the mlx_lm package with the lora command rather than the minimal lora example:

Docs here: https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md
