### ISSUE TITLE
(Q)LoRA training of Nemo Mistral failing with "ValueError: [transpose] Recived 1 axes for array with 2 dimensions."

### ISSUE THREAD

**Issue by chimezie** [ml-explore/mlx-examples#1168]
Steps to reproduce:

```commandline
mlx_lm.convert --hf-path mistralai/Mistral-Nemo-Instruct-2407 \
               --mlx-path /tmp/Mistral-Nemo-Instruct-2407-4bit-float32 \
               -q --dtype float32 --q-bits 4
```

Using config file:

```yaml
model: "/tmp/Mistral-Nemo-Instruct-2407-4bit-float32"

train: true
hf_dataset:
    name: "cogbuji/MrGrammaticalOntology_anatomist"
    train_split: "train[:100]"
    valid_split: "validation[-10:]"
    prompt_feature: "input"
    completion_feature: "output"
```

```commandline
% mlx_lm.lora -c /tmp/mlx_test_qlora.yaml                             
Loading configuration file /tmp/mlx_test_qlora.yaml
Loading pretrained model
Loading datasets
Loading Hugging Face dataset cogbuji/MrGrammaticalOntology_anatomist.
Training
Trainable parameters: 0.642% (78.643M/12247.782M)
Starting training..., iters: 1000
Iter 1: Val loss 4.802, Val took 2.807s
Traceback (most recent call last):
  File "/path/to/bin/mlx_lm.lora", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/to/mlx_lm/lora.py", line 291, in main
    run(types.SimpleNamespace(**args))
  File "/path/to/mlx_lm/lora.py", line 264, in run
    train_model(args, model, tokenizer, train_set, valid_set, training_callback)
  File "/path/to/mlx_lm/lora.py", line 220, in train_model
    train(
  File "/path/to/mlx_lm/tuner/trainer.py", line 271, in train
    lvalue, toks = step(batch)
                   ^^^^^^^^^^^
  File "/path/to/mlx_lm/tuner/trainer.py", line 210, in step
    (lvalue, toks), grad = loss_value_and_grad(model, *batch)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/mlx/nn/utils.py", line 35, in wrapped_value_grad_fn
    value, grad = value_grad_fn(model.trainable_parameters(), *args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [transpose] Recived 1 axes for array with 2 dimensions.
```

Git hashes:

```commandline
 mlx % git rev-parse --verify HEAD
a82996e9fbf42c8944cc8842c547ce560f4bbd04
 mlx-examples % git rev-parse --verify HEAD
dfa4dd6c93c4c2f81bfed6becb8af5cc3a89ae61
```

Run on the unquantized model (specified in command line OR changed in the LoRA config file):

```commandline
% mlx_lm.lora -c /tmp/mlx_test_qlora.yaml --model mistralai/Mistral-Nemo-Instruct-2407
Loading configuration file /tmp/mlx_test_qlora.yaml
Loading pretrained model
Fetching 16 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 24818.37it/s]
Loading datasets
Loading Hugging Face dataset cogbuji/MrGrammaticalOntology_anatomist.
Training
Trainable parameters: 0.642% (78.643M/12247.782M)
Starting training..., iters: 1000
Iter 1: Val loss 5.023, Val took 22.197s
Traceback (most recent call last):
  [..snip..]
  File "/path/to/mlx/nn/utils.py", line 35, in wrapped_value_grad_fn
    value, grad = value_grad_fn(model.trainable_parameters(), *args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [transpose] Recived 1 axes for array with 2 dimensions.
```

**Comment by awni** [comment]
Thanks for flagging. This was a recently introduced (not yet released bug). Fix is out.. should land soon.
