### ISSUE TITLE
Llama 2 conversion doesn't work (but should it?)

### ISSUE THREAD

**Issue by vladiliescu** [ml-explore/mlx-examples#18]
As the title says, I couldn't get a usable model for Llama 2 (specifically llama-2-13b). It's not clear whether the sample should only work with llama 1 (and if so, why? llama 2 has been around for quite a while) or also with llama 2.

Here are my steps

```sh
git clone https://github.com/ml-explore/mlx-examples.git

conda create -n mlx-experiments python=3.10 -y
conda activate mlx-experiments
pip install mlx==0.0.3

cd mlx-examples/llama
pip install -r requirements.txt

python convert.py /<path>/llama.cpp.2/models/llama-2-13b mlx_llama_weights.npz

> ModuleNotFoundError: No module named 'numpy'

pip install numpy

python convert.py /Users/vladi/Projects/llama.cpp.2/models/llama-2-13b mlx_llama_weights.npz

> IsADirectoryError: [Errno 21] Is a directory: '/<path>/Projects/llama.cpp.2/models/llama-2-13b'

python convert.py /Users/vladi/Projects/llama.cpp.2/models/llama-2-13b/consolidated.00.pth mlx_llama_weights.npz

> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

# add map_location=torch.device('mps') to torch.load

> TypeError: BFloat16 is not supported on MPS

# add map_location=torch.device('cpu')

> TypeError: Got unsupported ScalarType BFloat16

# replace "return key, value.numpy()" with "return key, value.numpy() if value.dtype != torch.bfloat16 else value.to(torch.float32).numpy()" as per https://github.com/ml-explore/mlx-examples/pull/10/commits/429ddb30dca199c9cfbfe2280cf47875cc3f0be9

python llama.py mlx_llama.npz tokenizer.model "hello"

> RuntimeError: [load] Failed to open file mlx_llama.npz

python llama.py mlx_llama_weights.npz tokenizer.model "hello"

(mlx-experiments) ➜  llama git:(main) ✗ python llama.py mlx_llama_weights.npz tokenizer.model "hello"
[INFO] Loading model from disk.
Press enter to start generation
------
Traceback (most recent call last):
  File "/<path>/Projects/mlx-examples/llama/llama.py", line 306, in <module>
    generate(args)
  File "/<path>/Projects/mlx-examples/llama/llama.py", line 180, in generate
    for token in model.generate(x, args.temp):
  File "/<path>/Projects/mlx-examples/llama/llama.py", line 125, in generate
    x, c = l(x, mask=mask)
  File "/<path>/Projects/mlx-examples/llama/llama.py", line 77, in __call__
    y = self.norm1(x)
  File "/<path>miniconda3/envs/mlx-experiments/lib/python3.10/site-packages/mlx/nn/layers/normalization.py", line 85, in __call__
    return self.weight * x * n
ValueError: Shapes (5120) and (1,2,2560) cannot be broadcast.

```

At this point I gave up in frustration and set a reminder three weeks from now to check the state of this project. 

I'm running an M2 Max with Ventura 13.6.2

EDIT: added `pip install -r requirements.txt`

**Comment by tanliboy** [comment]
I am running a similar problem on the Llama-7B-chat model with Apple M1 Pro + Ventura 13.6:

```
➜  llama git:(main) python convert.py ~/models/Llama-2-7b-chat/consolidated.00.pth ~/models/Llama-2-7b-chat/mlx_llama_weights.npz
Traceback (most recent call last):
  File "/<path>/llamaherder/mlx-examples/llama/convert.py", line 47, in <module>
    **{k: v for k, v in starmap(map_torch_to_mlx, state.items()) if k is not None}
  File "/<path>/mlx-examples/llama/convert.py", line 47, in <dictcomp>
    **{k: v for k, v in starmap(map_torch_to_mlx, state.items()) if k is not None}
  File "/<path>/mlx-examples/llama/convert.py", line 35, in map_torch_to_mlx
    return key, value.numpy()
TypeError: Got unsupported ScalarType BFloat16
```

**Comment by vladiliescu** [comment]
Installing a package with 10 stars is not a simple fix imo.

This might be a simple fix: https://twitter.com/pcuenq/status/1732424982654058559 .

**Comment by tanliboy** [comment]
Ya. That's a quick way.

**Comment by tanliboy** [comment]
Formal fix: https://github.com/ml-explore/mlx-examples/pull/10

**Comment by awni** [comment]
This should be fixed in main. Let us know if there are still any issues with Llama 2!
