### ISSUE TITLE
Qlora example fails with ValueError when using the latest mlx example code: dimension mismatch

### ISSUE THREAD

**Issue by PeterAronZentai** [ml-explore/mlx-examples#247]
This is a different issue than the one reported in https://github.com/ml-explore/mlx-examples/issues/228
I was following steps from README.md in `mlx-examples/lora`

Downloaded model and used below statements to convert in two flavours:

```sh
python convert.py --torch-path mistral-7B-v0.1 --mlx-path mlx-01
python convert.py --torch-path mistral-7B-v0.1 --mlx-path mlx-01-q -q
```

Lora model training works cool, but when I am trying the same with quantized model I am getting below error,

```sh
(base) ➜  lora git:(main) ✗ python lora.py --model mlx-01-q --train --iters 100
Loading pretrained model
Total parameters 1239.945M
Trainable parameters 1.704M
Loading datasets
Training
Traceback (most recent call last):
  File "/Users/z/Dev/weerobots/mlx-examples/lora/lora.py", line 386, in <module>
    train(model, train_set, valid_set, opt, loss, tokenizer, args)
  File "/Users/z/Dev/weerobots/mlx-examples/lora/lora.py", line 257, in train
    (lvalue, toks), grad = loss_value_and_grad(model, *batch)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/z/anaconda3/lib/python3.11/site-packages/mlx/nn/utils.py", line 30, in wrapped_value_grad_fn
    value, grad = value_grad_fn(model.trainable_parameters(), *args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/z/anaconda3/lib/python3.11/site-packages/mlx/nn/utils.py", line 25, in inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/z/Dev/weerobots/mlx-examples/lora/lora.py", line 182, in loss
    logits, _ = model(inputs)
                ^^^^^^^^^^^^^
  File "/Users/z/Dev/weerobots/mlx-examples/lora/models.py", line 199, in __call__
    return self.output(self.norm(h)), cache
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/z/anaconda3/lib/python3.11/site-packages/mlx/nn/layers/linear.py", line 66, in __call__
    x = x @ self.weight.T
        ~~^~~~~~~~~~~~~~~
ValueError: [matmul] Last dimension of first input with shape (4,105,4096) must match second to last dimension of second input with shape (512,32000).
```

I am using an M1 Max.

**Comment by awni** [comment]
Which conversion script did you use? The one in `lora` or the one in `llms/mistral`?

**Comment by PeterAronZentai** [comment]
@awni  huh you are right, I was using the converted model from llms/mistral - and indeed it works with converting with the script from lora. Apolgoies, I should have tried that out first. Thank you for your great work on this.

**Comment by awni** [comment]
Indeed - that said, the conversion from Mistral is actually better. We should really be quantizing the linear layer. So I'm still planning to merge the update in #250
