### ISSUE TITLE
"missing 5 required positional arguments" when I try to train using lora on llama2

### ISSUE THREAD

**Issue by Satyam7166-tech** [ml-explore/mlx-examples#283]
When I run :

```
python lora.py \
   --model ./mlx_model \
   --train \
   --iters 600 \
   --batch-size 1 \
   --lora-layers 4
```

I get the following error:

```
Loading pretrained model
Traceback (most recent call last):
  File "/Users/macstudiosct/projects/finetune_mlx/mlx-examples/lora/lora.py", line 297, in <module>
    model, tokenizer, _ = models.load(args.model)
  File "/Users/macstudiosct/projects/finetune_mlx/mlx-examples/lora/models.py", line 319, in load
    model_args = ModelArgs.from_dict(config)
  File "/Users/macstudiosct/projects/finetune_mlx/mlx-examples/lora/models.py", line 46, in from_dict
    return cls(
TypeError: ModelArgs.__init__() missing 5 required positional arguments: 'hidden_size', 'num_hidden_layers', 'intermediate_size', 'num_attention_heads', and 'rms_norm_eps'
```

I have also tried the arguments in the order mentioned in  `python lora.py -h`, no dice

System: 

M2 ultra with 128gb memory; 76 cores GPU.

Edit:

My mlx version is 0.07

**Comment by awni** [comment]
Did you pre-convert a model? If so can you share the command you used?

O/w you need to point the `--model` to a valid Hugging Face path like `--model mistralai/Mistral-7B-v0.1`.

**Comment by Satyam7166-tech** [comment]
I first downloaded llama2:7b from meta then used the convert.py script in mlx_examples/llms/llama

`python convert.py —-torch-path <torch path>`

**Comment by awni** [comment]
Right you should use the convert.py in the HF repo. Also note that converter only supports HF style models. Your best bet is to point it at the HF repo directly (for example https://huggingface.co/meta-llama/Llama-2-7b-hf). The examples have diverged so the output of that convert will not work with the HF format models :\.

**Comment by Satyam7166-tech** [comment]
Ah I see.

But is there a way to use a preconverted model instead of using the hugging face path?

Thanks a lot for your help.

**Comment by awni** [comment]
> The convert.py is mostly there to make quantized models or change the data type (and optionally upload the quantized models to Hugging Face)

```
python convert.py --hf-path <model> -q
```

**Comment by Satyam7166-tech** [comment]
Hello @awni, I just tried this for llama2:70b
> ```
> python convert.py --hf-path <model> -q
> ```

I ran this in `mlx_examples/lora` My exact command was:

`python convert.py --hf-path meta-llama/Llama-2-70b-chat-hf -q --mlx-path ./`


But I recieved an error. This is my trace:

```
INFO] Loading
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 614/614 [00:00<00:00, 5.96MB/s]
generation_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 188/188 [00:00<00:00, 781kB/s]
model-00008-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [54:38<00:00, 2.99MB/s]
model-00006-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [56:31<00:00, 2.89MB/s]
model-00002-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:02:40<00:00, 2.61MB/s]
model-00005-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:11:26<00:00, 2.29MB/s]
model-00007-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.97G/9.97G [1:28:44<00:00, 1.87MB/s]
model-00009-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [56:14<00:00, 2.90MB/s]
model-00010-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [58:25<00:00, 2.80MB/s]
model-00015-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 524M/524M [02:58<00:00, 2.93MB/s]
model.safetensors.index.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 66.7k/66.7k [00:00<00:00, 1.26MB/s]
pytorch_model.bin.index.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 66.7k/66.7k [00:00<00:00, 3.69MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 414/414 [00:00<00:00, 1.27MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 2.39MB/s]
tokenizer.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 1.14MB/s]
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.62k/1.62k [00:00<00:00, 9.31MB/s]
model-00001-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.85G/9.85G [2:02:39<00:00, 1.34MB/s]
model-00011-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.97G/9.97G [1:09:53<00:00, 2.38MB/s]
model-00012-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:05:47<00:00, 2.48MB/s]
model-00003-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.97G/9.97G [2:21:51<00:00, 1.17MB/s]
model-00013-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:00:43<00:00, 2.69MB/s]
model-00004-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [2:31:38<00:00, 1.08MB/s]
model-00014-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.50G/9.50G [40:46<00:00, 3.88MB/s]
Fetching 23 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [2:31:43<00:00, 395.79s/it]
[INFO] Quantizing015.safetensors:  78%|████████████████████████████████████████████████████████████████████████████▉                      | 7.61G/9.80G [53:05<09:15, 3.94MB/s]
Traceback (most recent call last):100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:00:43<00:00, 5.40MB/s]
  File "/Users/macstudiosct/projects/finetune_mlx/mlx-examples/lora/convert.py", line 89, in <module>█████████████████████████▍         | 8.83G/9.80G [2:29:27<03:07, 5.16MB/s]
    weights, config = quantize(weights, config, args)███████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [2:31:38<00:00, 6.33MB/s]
  File "/Users/macstudiosct/projects/finetune_mlx/mlx-examples/lora/convert.py", line 18, in quantize██████████████████████████▋          | 8.50G/9.50G [38:30<03:21, 4.92MB/s]
    model.load_weights(list(weights.items()))████████████████████████████████████████████████████████████████████████████████████████████▎| 9.43G/9.50G [40:41<00:09, 7.25MB/s]
  File "/Users/macstudiosct/projects/finetune_mlx/mlx1/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 146, in load_weights█████| 9.50G/9.50G [40:46<00:00, 12.0MB/s]
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.30.self_attn.rotary_emb.inv_freq model.layers.47.self_attn.rotary_emb.inv_freq model.layers.17.self_attn.rotary_emb.inv_freq model.layers.58.self_attn.rotary_emb.inv_freq model.layers.28.self_attn.rotary_emb.inv_freq model.layers.21.self_attn.rotary_emb.inv_freq model.layers.45.self_attn.rotary_emb.inv_freq model.layers.59.self_attn.rotary_emb.inv_freq model.layers.11.self_attn.rotary_emb.inv_freq model.layers.2.self_attn.rotary_emb.inv_freq model.layers.52.self_attn.rotary_emb.inv_freq model.layers.18.self_attn.rotary_emb.inv_freq model.layers.49.self_attn.rotary_emb.inv_freq model.layers.78.self_attn.rotary_emb.inv_freq model.layers.62.self_attn.rotary_emb.inv_freq model.layers.48.self_attn.rotary_emb.inv_freq model.layers.64.self_attn.rotary_emb.inv_freq model.layers.73.self_attn.rotary_emb.inv_freq model.layers.20.self_attn.rotary_emb.inv_freq model.layers.0.self_attn.rotary_emb.inv_freq model.layers.39.self_attn.rotary_emb.inv_freq model.layers.1.self_attn.rotary_emb.inv_freq model.layers.35.self_attn.rotary_emb.inv_freq model.layers.7.self_attn.rotary_emb.inv_freq model.layers.70.self_attn.rotary_emb.inv_freq model.layers.79.self_attn.rotary_emb.inv_freq model.layers.8.self_attn.rotary_emb.inv_freq model.layers.29.self_attn.rotary_emb.inv_freq model.layers.74.self_attn.rotary_emb.inv_freq model.layers.67.self_attn.rotary_emb.inv_freq model.layers.6.self_attn.rotary_emb.inv_freq model.layers.4.self_attn.rotary_emb.inv_freq model.layers.34.self_attn.rotary_emb.inv_freq model.layers.56.self_attn.rotary_emb.inv_freq model.layers.54.self_attn.rotary_emb.inv_freq model.layers.77.self_attn.rotary_emb.inv_freq model.layers.22.self_attn.rotary_emb.inv_freq model.layers.32.self_attn.rotary_emb.inv_freq model.layers.50.self_attn.rotary_emb.inv_freq model.layers.16.self_attn.rotary_emb.inv_freq model.layers.53.self_attn.rotary_emb.inv_freq model.layers.55.self_attn.rotary_emb.inv_freq model.layers.24.self_attn.rotary_emb.inv_freq model.layers.57.self_attn.rotary_emb.inv_freq model.layers.61.self_attn.rotary_emb.inv_freq model.layers.15.self_attn.rotary_emb.inv_freq model.layers.41.self_attn.rotary_emb.inv_freq model.layers.33.self_attn.rotary_emb.inv_freq model.layers.25.self_attn.rotary_emb.inv_freq model.layers.38.self_attn.rotary_emb.inv_freq model.layers.14.self_attn.rotary_emb.inv_freq model.layers.10.self_attn.rotary_emb.inv_freq model.layers.51.self_attn.rotary_emb.inv_freq model.layers.5.self_attn.rotary_emb.inv_freq model.layers.3.self_attn.rotary_emb.inv_freq model.layers.37.self_attn.rotary_emb.inv_freq model.layers.69.self_attn.rotary_emb.inv_freq model.layers.26.self_attn.rotary_emb.inv_freq model.layers.71.self_attn.rotary_emb.inv_freq model.layers.23.self_attn.rotary_emb.inv_freq model.layers.42.self_attn.rotary_emb.inv_freq model.layers.31.self_attn.rotary_emb.inv_freq model.layers.63.self_attn.rotary_emb.inv_freq model.layers.75.self_attn.rotary_emb.inv_freq model.layers.43.self_attn.rotary_emb.inv_freq model.layers.40.self_attn.rotary_emb.inv_freq model.layers.19.self_attn.rotary_emb.inv_freq model.layers.68.self_attn.rotary_emb.inv_freq model.layers.44.self_attn.rotary_emb.inv_freq model.layers.46.self_attn.rotary_emb.inv_freq model.layers.72.self_attn.rotary_emb.inv_freq model.layers.27.self_attn.rotary_emb.inv_freq model.layers.60.self_attn.rotary_emb.inv_freq model.layers.12.self_attn.rotary_emb.inv_freq model.layers.9.self_attn.rotary_emb.inv_freq model.layers.66.self_attn.rotary_emb.inv_freq model.layers.13.self_attn.rotary_emb.inv_freq model.layers.76.self_attn.rotary_emb.inv_freq model.layers.65.self_attn.rotary_emb.inv_freq model.layers.36.self_attn.rotary_emb.inv_freq.

```

Can you please help me out here? Not sure how to solve this. My purpose is to finetune a llama2:70b model using qlora. I understand it will be very very slow or I may run out of memory  but I'd like to try anyway.

I encountered a similar error when trying to finetune mixtral (I ran convert.py directly without quantisation). However from what I understand, there is no support for mixtral yet.

**Comment by awni** [comment]
You have to use the Hugging Face version not the original Meta version. So in your case that would be https://huggingface.co/meta-llama/Llama-2-70b-chat-hf

**Comment by awni** [comment]
Also fine-tuning a 70B is impressive! I hope that runs fast enough for you 🤞

**Comment by Satyam7166-tech** [comment]
> You have to use the Hugging Face version not the original Meta version. So in your case that would be https://huggingface.co/meta-llama/Llama-2-70b-chat-hf

Ah but as you can see in code, I use the hugging face version here.

**Comment by awni** [comment]
Oh i see, sorry I read your initial message too quickly. The issue is we aren't handling these params:

`model.layers.47.self_attn.rotary_emb.inv_freq` 

That requires some work to figure out.

**Comment by Satyam7166-tech** [comment]
So should I create a new issue with this?
Also, do you know of any other 70B that works with mlx qlora ?

**Comment by awni** [comment]
@mzbac do you happen to know where those `inv_freq` parameters are supposed to go?

@Satyam7166-tech  I haven't tested a 70B model with LoRA so I can't point you to one that I feel confident works, but I suspect it should be a quick fix to get those parameters in.

**Comment by awni** [comment]
> So should I create a new issue with this?

Yes that would be helpful so we can track it, it's different from the top of this issue

**Comment by Satyam7166-tech** [comment]
> > So should I create a new issue with this?
> 
> Yes that would be helpful so we can track it, it's different from the top of this issue

Ok creating an issue now. Thanks for all your support :-)

**Comment by Satyam7166-tech** [comment]
> > So should I create a new issue with this?
> 
> Yes that would be helpful so we can track it, it's different from the top of this issue

Ok creating an issue now. Thanks for all your support :-)

**Comment by mzbac** [comment]
> @mzbac do you happen to know where those `inv_freq` parameters are supposed to go?
> 
> @Satyam7166-tech I haven't tested a 70B model with LoRA so I can't point you to one that I feel confident works, but I suspect it should be a quick fix to get those parameters in.

@awni MLX is using a different rope implementation ([here](https://github.com/mzbac/mlx/blob/de13a5dd330cbcefd50a724df5c54909431ac914/python/mlx/nn/layers/positional_encoding.py#L10) is a comparison if we want to implement it in MLX's rope), so we don't prebuild the freq for the rope embedding. Instead, we build a slice of freq per token generation.

**Comment by Satyam7166-tech** [comment]
Most of what you guys spoke about went right over my head :) But well, it just shows how far I have to go.

I will apply the temporary fix though and will research a bit to understand the long one.
