### ISSUE TITLE
TypeError: ModelArgs.__init__() missing 5 required positional arguments [..]

### ISSUE THREAD

**Issue by chimezie** [ml-explore/mlx-examples#298]
Running the following command-line from main (changeset a2402116ae6201264f683259046741ce8fac39e7 with mlx-examples/lora as the working directory)

    python lora.py --model /some/path/ --temp 0.2 --prompt "A prompt" --train --data /my/path/ --batch-size 12 --iters 1284 --val-batches 79 --adapter-file /some/path/weights.npz

Full traceback:

```python
Loading pretrained model
Traceback (most recent call last):
  File "/Users/oori/medical_llm/mlx-examples/lora/lora.py", line 297, in <module>
    model, tokenizer, _ = models.load(args.model)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oori/medical_llm/mlx-examples/lora/models.py", line 319, in load
    model_args = ModelArgs.from_dict(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oori/medical_llm/mlx-examples/lora/models.py", line 46, in from_dict
    return cls(
           ^^^^
TypeError: ModelArgs.__init__() missing 5 required positional arguments: 'hidden_size', 'num_hidden_layers', 'intermediate_size', 'num_attention_heads', and 'rms_norm_eps'```

**Comment by awni** [comment]
Closing, let me know if you still have any issues and I can reopen.
