### ISSUE TITLE
Phi-2 broken with official model

### ISSUE THREAD

**Issue by yousifa** [ml-explore/mlx-examples#299]
Running the demo command for phi-2 fails with the current mlx release (0.0.7)

```shell
> python3 generate.py --model microsoft/phi-2 --prompt "hello"

Traceback (most recent call last):
  File "mlx-examples/llms/phi2/generate.py", line 90, in <module>
    model, tokenizer = phi2.load(args.model)
                       ^^^^^^^^^^^^^^^^^^^^^
  File "mlx-examples/llms/phi2/phi2.py", line 218, in load
    model.load_weights(list(weights.items()))
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 146, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.25.input_layernorm.weight model.layers.21.self_attn.v_proj.bias model.layers.29.input_layernorm.bias model.layers.20.input_layernorm.bias model.layers.7.self_attn.v_proj.weight model.layers.14.self_attn.v_proj.weight
```

**Comment by awni** [comment]
Try using [`hf_llm/generate.py`](https://github.com/ml-explore/mlx-examples/blob/main/llms/hf_llm/generate.py) instead (we just merged support for phi2). The Hugging Face repo has changed which I think broke things, and we have also deprecated that file.

**Comment by yousifa** [comment]
it's broken with hf_llm generate as well:

```shell
Traceback (most recent call last):
  File "mlx-examples/llms/hf_llm/generate.py", line 87, in <module>
    model, tokenizer = models.load(args.model)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "mlx-examples/llms/hf_llm/models.py", line 235, in load
    model_args = ModelArgs.from_dict(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlx-examples/llms/hf_llm/models.py", line 44, in from_dict
    return cls(
           ^^^^
TypeError: ModelArgs.__init__() missing 1 required positional argument: 'rms_norm_eps'
``` 

TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T is also broken (no safetensors found)

**Comment by awni** [comment]
That is not an MLX issue. That repo seems to have removed the safetensors for some reason 🤷 

https://huggingface.co/TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T/tree/main

**Comment by yousifa** [comment]
Understand, but should maybe remove it from the readme for hf_llm
