### ISSUE TITLE
Throws a "received parameters not in model" error when trying to convert llama2:70b hf to 4 bit npz

### ISSUE THREAD

**Issue by Satyam7166-tech** [ml-explore/mlx-examples#305]
I was trying to convert llama2:70b hf to 4bit quantisation for performing Qlora finetuning. 
> ```
> python convert.py --hf-path <model> -q
> ```

I ran this in `mlx_examples/lora` My exact command was:

`python convert.py --hf-path meta-llama/Llama-2-70b-chat-hf -q --mlx-path ./`

But I recieved an error. This is my trace:

```
INFO] Loading
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 614/614 [00:00<00:00, 5.96MB/s]
generation_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 188/188 [00:00<00:00, 781kB/s]
model-00008-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [54:38<00:00, 2.99MB/s]
model-00006-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [56:31<00:00, 2.89MB/s]
model-00002-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:02:40<00:00, 2.61MB/s]
model-00005-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:11:26<00:00, 2.29MB/s]
model-00007-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.97G/9.97G [1:28:44<00:00, 1.87MB/s]
model-00009-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [56:14<00:00, 2.90MB/s]
model-00010-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [58:25<00:00, 2.80MB/s]
model-00015-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 524M/524M [02:58<00:00, 2.93MB/s]
model.safetensors.index.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 66.7k/66.7k [00:00<00:00, 1.26MB/s]
pytorch_model.bin.index.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 66.7k/66.7k [00:00<00:00, 3.69MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 414/414 [00:00<00:00, 1.27MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 2.39MB/s]
tokenizer.model: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 1.14MB/s]
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.62k/1.62k [00:00<00:00, 9.31MB/s]
model-00001-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.85G/9.85G [2:02:39<00:00, 1.34MB/s]
model-00011-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.97G/9.97G [1:09:53<00:00, 2.38MB/s]
model-00012-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:05:47<00:00, 2.48MB/s]
model-00003-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.97G/9.97G [2:21:51<00:00, 1.17MB/s]
model-00013-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:00:43<00:00, 2.69MB/s]
model-00004-of-00015.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [2:31:38<00:00, 1.08MB/s]
model-00014-of-00015.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 9.50G/9.50G [40:46<00:00, 3.88MB/s]
Fetching 23 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [2:31:43<00:00, 395.79s/it]
[INFO] Quantizing015.safetensors:  78%|████████████████████████████████████████████████████████████████████████████▉                      | 7.61G/9.80G [53:05<09:15, 3.94MB/s]
Traceback (most recent call last):100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [1:00:43<00:00, 5.40MB/s]
  File "/Users/macstudiosct/projects/finetune_mlx/mlx-examples/lora/convert.py", line 89, in <module>█████████████████████████▍         | 8.83G/9.80G [2:29:27<03:07, 5.16MB/s]
    weights, config = quantize(weights, config, args)███████████████████████████████████████████████████████████████████████████████████| 9.80G/9.80G [2:31:38<00:00, 6.33MB/s]
  File "/Users/macstudiosct/projects/finetune_mlx/mlx-examples/lora/convert.py", line 18, in quantize██████████████████████████▋          | 8.50G/9.50G [38:30<03:21, 4.92MB/s]
    model.load_weights(list(weights.items()))████████████████████████████████████████████████████████████████████████████████████████████▎| 9.43G/9.50G [40:41<00:09, 7.25MB/s]
  File "/Users/macstudiosct/projects/finetune_mlx/mlx1/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 146, in load_weights█████| 9.50G/9.50G [40:46<00:00, 12.0MB/s]
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.30.self_attn.rotary_emb.inv_freq model.layers.47.self_attn.rotary_emb.inv_freq model.layers.17.self_attn.rotary_emb.inv_freq model.layers.58.self_attn.rotary_emb.inv_freq model.layers.28.self_attn.rotary_emb.inv_freq model.layers.21.self_attn.rotary_emb.inv_freq model.layers.45.self_attn.rotary_emb.inv_freq model.layers.59.self_attn.rotary_emb.inv_freq model.layers.11.self_attn.rotary_emb.inv_freq model.layers.2.self_attn.rotary_emb.inv_freq model.layers.52.self_attn.rotary_emb.inv_freq model.layers.18.self_attn.rotary_emb.inv_freq model.layers.49.self_attn.rotary_emb.inv_freq model.layers.78.self_attn.rotary_emb.inv_freq model.layers.62.self_attn.rotary_emb.inv_freq model.layers.48.self_attn.rotary_emb.inv_freq model.layers.64.self_attn.rotary_emb.inv_freq model.layers.73.self_attn.rotary_emb.inv_freq model.layers.20.self_attn.rotary_emb.inv_freq model.layers.0.self_attn.rotary_emb.inv_freq model.layers.39.self_attn.rotary_emb.inv_freq model.layers.1.self_attn.rotary_emb.inv_freq model.layers.35.self_attn.rotary_emb.inv_freq model.layers.7.self_attn.rotary_emb.inv_freq model.layers.70.self_attn.rotary_emb.inv_freq model.layers.79.self_attn.rotary_emb.inv_freq model.layers.8.self_attn.rotary_emb.inv_freq model.layers.29.self_attn.rotary_emb.inv_freq model.layers.74.self_attn.rotary_emb.inv_freq model.layers.67.self_attn.rotary_emb.inv_freq model.layers.6.self_attn.rotary_emb.inv_freq model.layers.4.self_attn.rotary_emb.inv_freq model.layers.34.self_attn.rotary_emb.inv_freq model.layers.56.self_attn.rotary_emb.inv_freq model.layers.54.self_attn.rotary_emb.inv_freq model.layers.77.self_attn.rotary_emb.inv_freq model.layers.22.self_attn.rotary_emb.inv_freq model.layers.32.self_attn.rotary_emb.inv_freq model.layers.50.self_attn.rotary_emb.inv_freq model.layers.16.self_attn.rotary_emb.inv_freq model.layers.53.self_attn.rotary_emb.inv_freq model.layers.55.self_attn.rotary_emb.inv_freq model.layers.24.self_attn.rotary_emb.inv_freq model.layers.57.self_attn.rotary_emb.inv_freq model.layers.61.self_attn.rotary_emb.inv_freq model.layers.15.self_attn.rotary_emb.inv_freq model.layers.41.self_attn.rotary_emb.inv_freq model.layers.33.self_attn.rotary_emb.inv_freq model.layers.25.self_attn.rotary_emb.inv_freq model.layers.38.self_attn.rotary_emb.inv_freq model.layers.14.self_attn.rotary_emb.inv_freq model.layers.10.self_attn.rotary_emb.inv_freq model.layers.51.self_attn.rotary_emb.inv_freq model.layers.5.self_attn.rotary_emb.inv_freq model.layers.3.self_attn.rotary_emb.inv_freq model.layers.37.self_attn.rotary_emb.inv_freq model.layers.69.self_attn.rotary_emb.inv_freq model.layers.26.self_attn.rotary_emb.inv_freq model.layers.71.self_attn.rotary_emb.inv_freq model.layers.23.self_attn.rotary_emb.inv_freq model.layers.42.self_attn.rotary_emb.inv_freq model.layers.31.self_attn.rotary_emb.inv_freq model.layers.63.self_attn.rotary_emb.inv_freq model.layers.75.self_attn.rotary_emb.inv_freq model.layers.43.self_attn.rotary_emb.inv_freq model.layers.40.self_attn.rotary_emb.inv_freq model.layers.19.self_attn.rotary_emb.inv_freq model.layers.68.self_attn.rotary_emb.inv_freq model.layers.44.self_attn.rotary_emb.inv_freq model.layers.46.self_attn.rotary_emb.inv_freq model.layers.72.self_attn.rotary_emb.inv_freq model.layers.27.self_attn.rotary_emb.inv_freq model.layers.60.self_attn.rotary_emb.inv_freq model.layers.12.self_attn.rotary_emb.inv_freq model.layers.9.self_attn.rotary_emb.inv_freq model.layers.66.self_attn.rotary_emb.inv_freq model.layers.13.self_attn.rotary_emb.inv_freq model.layers.76.self_attn.rotary_emb.inv_freq model.layers.65.self_attn.rotary_emb.inv_freq model.layers.36.self_attn.rotary_emb.inv_freq.

```

            
Edit for better tracking:

_Originally posted by @Satyam7166-tech in https://github.com/ml-explore/mlx-examples/issues/283#issuecomment-1888382673_

**Comment by mzbac** [comment]
The inv_freq weight is not really needed for the MLX Llama example. A quick workaround would be to change line 18 in convert.py to `model.load_weights(list(weights.items()), strict=False)`.

**Comment by jvroth18** [comment]
Thank you @mzbac ! 

I received this error while trying to fine-tune "mistralai/Mixtral-8x7B-v0.1" on a custom dataset. The error is: 

`ValueError: Received parameters not in model: model.layers.1.block_sparse_moe.experts.6.w3.weight model.layers.11.block_sparse_moe.experts.5.w3.weight model.layers.25.block_sparse_moe.experts.3.w3.weight`

Do you have any idea why this might be happening?

**Comment by mzbac** [comment]
> Thank you @mzbac !
> 
> I received this error while trying to fine-tune "mistralai/Mixtral-8x7B-v0.1" on a custom dataset. The error is:
> 
> `ValueError: Received parameters not in model: model.layers.1.block_sparse_moe.experts.6.w3.weight model.layers.11.block_sparse_moe.experts.5.w3.weight model.layers.25.block_sparse_moe.experts.3.w3.weight`
> 
> Do you have any idea why this might be happening?

I don't think the current Lora supports Mixtral yet. It only supports llama-like models and Phi2 at the moment. Currently, I am trying to work on moving all the hf model examples to mlx-lm. Maybe after we have a unified way to load the models, we can start updating lora example to support more models.

**Comment by marcelbischoff** [comment]
Getting the same error for `load("meta-llama/Llama-2-7b-chat-hf")`

**Comment by marcelbischoff** [comment]
`strict=False` fixes it!

**Comment by awni** [comment]
Correct, those params are not needed by our model. We should pop them from the weights so that one can use them as is. I will update the example to do so!

**Comment by awni** [comment]
We compute them on the fly.
