### ISSUE TITLE
lora convert.py quantize error

### ISSUE THREAD

**Issue by gladjoyhub** [ml-explore/mlx-examples#317]
(base) joy@Mac-Studio lora % python3 convert.py --hf-path upstage/SOLAR-10.7B-Instruct-v1.0 -q --q-bits 5 --q-group-size 32
[INFO] Loading
Fetching 11 files: 100%|████████████████████████████████| 11/11 [00:00<00:00, 161885.42it/s]
[INFO] Quantizing
Traceback (most recent call last):
  File "/Users/joy/mlx-examples-main/lora/convert.py", line 91, in <module>
    weights, config = quantize(weights, config, args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/mlx-examples-main/lora/convert.py", line 23, in quantize
    nn.QuantizedLinear.quantize_module(model, args.q_group_size, args.q_bits)
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/nn/layers/quantized.py", line 124, in quantize_module
    leaves = tree_map(_quantize_if_linear, leaves, is_leaf=Module.is_module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 49, in tree_map
    return {
           ^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 50, in <dictcomp>
    k: tree_map(fn, child, *(r[k] for r in rest), is_leaf=is_leaf)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 49, in tree_map
    return {
           ^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 50, in <dictcomp>
    k: tree_map(fn, child, *(r[k] for r in rest), is_leaf=is_leaf)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 44, in tree_map
    return TreeType(
           ^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 45, in <genexpr>
    tree_map(fn, child, *(r[i] for r in rest), is_leaf=is_leaf)
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 49, in tree_map
    return {
           ^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 50, in <dictcomp>
    k: tree_map(fn, child, *(r[k] for r in rest), is_leaf=is_leaf)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 49, in tree_map
    return {
           ^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 50, in <dictcomp>
    k: tree_map(fn, child, *(r[k] for r in rest), is_leaf=is_leaf)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/utils.py", line 41, in tree_map
    return fn(tree, *rest)
           ^^^^^^^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/nn/layers/quantized.py", line 119, in _quantize_if_linear
    return cls.from_linear(m, group_size, bits)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/nn/layers/quantized.py", line 100, in from_linear
    ql = cls(input_dims, output_dims, False, group_size, bits)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joy/miniconda3/lib/python3.11/site-packages/mlx/nn/layers/quantized.py", line 58, in __init__
    self.weight, self.scales, self.biases = mx.quantize(weight, group_size, bits)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Cannot reshape array of size 16777216 into shape (4096,682,6).

**Comment by awni** [comment]
Thanks @mzbac ! We should throw for now when attempting 5-bit (will update that in our quantizer).

**Comment by gladjoyhub** [comment]
Yes, I changed q_bits to 8 and successfully got the quantized model.

But then I tried to fine-tune it with lora, I got this error:

(base) joy@Mac-Studio lora % python lora.py --model /Users/joy/Downloads/mlx_model/solar_q8 --adapter-file /Users/joy/Downloads/mlx_adapter/solar_q8_lora.npz --train --iters 10000 --batch-size 1 --learning-rate 1e-5
Loading pretrained model
Total parameters 3445.690M
Trainable parameters 1.704M
Loading datasets
Training
libc++abi: terminating due to uncaught exception of type std::runtime_error: [metal::Device] Unable to load kernel qmm_t_float16_gs_32_b_8

zsh: abort      python lora.py --model /Users/joy/Downloads/mlx_model/solar_q8 --adapter-file

**Comment by gladjoyhub** [comment]
Yes, I removed --q-group-size 32, now the quantized model can generate

**Comment by awni** [comment]
Great, latest MLX now throws for unsupported cases, so I am closing this as resolved for now.
