### ISSUE TITLE
Unable to run Phi2 example

### ISSUE THREAD

**Issue by michaelgruner** [ml-explore/mlx-examples#328]
Command:
```
python3 generate.py --model microsoft/phi-2 --prompt "hello"
```

It did download the model.

Output:
```
Fetching 10 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 35575.10it/s]
Traceback (most recent call last):
  File "/Users/mgruner/RidgeRun/AI/mlx-examples/llms/phi2/generate.py", line 90, in <module>
    model, tokenizer = phi2.load(args.model)
  File "/Users/mgruner/RidgeRun/AI/mlx-examples/llms/phi2/phi2.py", line 218, in load
    model.load_weights(list(weights.items()))
  File "/Users/mgruner/.pyenv/versions/mlx/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 146, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.4.mlp.fc2.weight model.layers.10.mlp.fc2.weight model.layers.4.mlp.fc1.bias ...
```

Environment:
```
python3 --version
Python 3.10.11

pip3 freeze
certifi==2023.11.17
charset-normalizer==3.3.2
einops==0.7.0
filelock==3.13.1
fsspec==2023.12.2
huggingface-hub==0.20.2
idna==3.6
Jinja2==3.1.2
MarkupSafe==2.1.3
mlx==0.0.7
mpmath==1.3.0
networkx==3.2.1
numpy==1.26.3
packaging==23.2
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
safetensors==0.4.1
sentencepiece==0.1.99
sympy==1.12
tokenizers==0.15.0
torch==2.1.2
tqdm==4.66.1
transformers==4.36.2
typing_extensions==4.9.0
urllib3==2.1.0
```

**Comment by michaelgruner** [comment]
Same happens if I run the model locally:

```python3 ./generate.py --model ~/.cache/huggingface/hub/models--microsoft--phi-2/snapshots/1a4c7ae2ef255229278ef3f015ff3aa6d758b5ee/ --prompt "hello"
Traceback (most recent call last):
  File "/Users/mgruner/RidgeRun/AI/mlx-examples/llms/phi2/./generate.py", line 90, in <module>
    model, tokenizer = phi2.load(args.model)
  File "/Users/mgruner/RidgeRun/AI/mlx-examples/llms/phi2/phi2.py", line 218, in load
    model.load_weights(list(weights.items()))
  File "/Users/mgruner/.pyenv/versions/mlx/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 148, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.30.self_attn.k_proj.bias model.layers.17.self_attn.v_proj.bias model.final_layernorm.bias model.layers.7.mlp.fc2.weight ...
```

**Comment by michaelgruner** [comment]
Update 3:

Same happens if I download the model manually:

```
git clone https://huggingface.co/microsoft/phi-2
Cloning into 'phi-2'...
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 90 (delta 39), reused 0 (delta 0), pack-reused 11
Unpacking objects: 100% (90/90), 1.14 MiB | 3.54 MiB/s, done.
Filtering content: 100% (2/2), 1.17 GiB | 2.19 MiB/s, done.

python3 ./generate.py --model phi-2/ --prompt "hello"
Traceback (most recent call last):
  File "/Users/mgruner/RidgeRun/AI/mlx-examples/llms/phi2/./generate.py", line 90, in <module>
    model, tokenizer = phi2.load(args.model)
  File "/Users/mgruner/RidgeRun/AI/mlx-examples/llms/phi2/phi2.py", line 218, in load
    model.load_weights(list(weights.items()))
  File "/Users/mgruner/.pyenv/versions/mlx/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 148, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.20.self_attn.dense.bias model.layers.25.mlp.fc2.weight model.layers.30.mlp.fc2.bias ...
```

**Comment by mzbac** [comment]
Looks like you are using the old example. Would you try pulling the latest code from main?

**Comment by awni** [comment]
Let us know if you still have issues after updating and I will reopen.

**Comment by michaelgruner** [comment]
I confirm updating to the latest example works. Thanks for the quick answer.

For anyone reading along, here’s the equivalent command:

```
cd llms
python -m mlx_lm.generate --model microsoft/phi-2 --prompt "hello"
```

**Comment by awni** [comment]
FWIW you can also just do:

```
pip install mlx-lm
```

And then use the generate command as you've written it.
