### ISSUE TITLE
stable_diffusion : `ValueError: Shapes (2,127,1024) and (77,1024) cannot be broadcast.` with long prompts

### ISSUE THREAD

**Issue by ringsaturn** [ml-explore/mlx-examples#34]
Short description: a long prompts text could cause `cannot be broadcast error`:

```
prompts = (
    "A picturesque and pristine view of San Francisco, capturing the essence of a"
    "clean and beautiful city. The illustration should depict the iconic landmarks of"
    "San Francisco, like the Golden Gate Bridge, the Transamerica Pyramid, and the"
    "Painted Ladies Victorian houses. The scene is bathed in a warm, golden sunlight,"
    "enhancing the city's charm. Streets are clean, with lush green parks and vibrant"
    "flowers in bloom, showcasing a community that takes pride in their environment."
    "The bay area is visible in the background, with clear blue waters and a peaceful"
    "atmosphere, conveying a sense of harmony and unity within the city."
)
```

Output:

```
  0%|                                                                                                                                                   | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/xxxxx/stable_diffusion/demo.py", line 61, in <module>
    for x_t in tqdm(latents, total=args.steps):
  File "/xxxxx/venv/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/xxxxx/stable_diffusion/stable_diffusion/__init__.py", line 68, in generate_latents
    conditioning = self.text_encoder(tokens)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxxxx/stable_diffusion/stable_diffusion/clip.py", line 62, in __call__
    x = x + self.position_embedding.weight[:N]
        ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ValueError: Shapes (2,127,1024) and (77,1024) cannot be broadcast.
```

---

Full code:

```py
import argparse
from PIL import Image
from tqdm import tqdm

import mlx.core as mx

from stable_diffusion import StableDiffusion

prompts = (
    "A picturesque and pristine view of San Francisco, capturing the essence of a"
    "clean and beautiful city. The illustration should depict the iconic landmarks of"
    "San Francisco, like the Golden Gate Bridge, the Transamerica Pyramid, and the"
    "Painted Ladies Victorian houses. The scene is bathed in a warm, golden sunlight,"
    "enhancing the city's charm. Streets are clean, with lush green parks and vibrant"
    "flowers in bloom, showcasing a community that takes pride in their environment."
    "The bay area is visible in the background, with clear blue waters and a peaceful"
    "atmosphere, conveying a sense of harmony and unity within the city."
)

parser = argparse.ArgumentParser(
    description="Generate images from a textual prompt using stable diffusion"
)
parser.add_argument("--n_images", type=int, default=1)
parser.add_argument("--steps", type=int, default=50)
parser.add_argument("--cfg", type=float, default=7.5)
parser.add_argument("--negative_prompt", default="")
parser.add_argument("--n_rows", type=int, default=1)
parser.add_argument("--decoding_batch_size", type=int, default=1)
parser.add_argument("--output", default="demo_out.png")
args = parser.parse_args()

sd = StableDiffusion()

# Generate the latent vectors using diffusion
latents = sd.generate_latents(
    prompts,
    n_images=args.n_images,
    cfg_weight=args.cfg,
    num_steps=args.steps,
    negative_text=args.negative_prompt,
)
for x_t in tqdm(latents, total=args.steps):
    mx.simplify(x_t)
    mx.simplify(x_t)
    mx.eval(x_t)

# Decode them into images
decoded = []
for i in tqdm(range(0, args.n_images, args.decoding_batch_size)):
    decoded.append(sd.decode(x_t[i : i + args.decoding_batch_size]))
    mx.eval(decoded[-1])

# Arrange them on a grid
x = mx.concatenate(decoded, axis=0)
x = mx.pad(x, [(0, 0), (8, 8), (8, 8), (0, 0)])
B, H, W, C = x.shape
x = x.reshape(args.n_rows, B // args.n_rows, H, W, C).transpose(0, 2, 1, 3, 4)
x = x.reshape(args.n_rows * H, B // args.n_rows * W, C)
x = (x * 255).astype(mx.uint8)

# Save them to disc
im = Image.fromarray(x.__array__())
im.save(args.output)
```

requirements version:

```
charset-normalizer 3.3.2
llvmlite           0.41.1
mlx                0.0.3
more-itertools     10.1.0
mpmath             1.3.0
numba              0.58.1
numpy              1.26.2
sympy              1.12
tqdm               4.66.1
```

**Comment by angeloskath** [comment]
That is a limitation of the available weights unfortunately. The clip text encoder can support up to 77 tokens of prompt while yours results in 127.

I am not sure what you should do if you really need prompts that big with this encoder. Interpolating the positional encodings may work but it also may not work at all. Something like the following

```python
def interp(x, y):
    left = x.astype(mx.int32)
    right = mx.minimum(left + 1, len(y) - 1)
    d_left = x - left
    d_right = right - x
    w_left = d_left / (d_left + d_right)
    w_right = 1 - w_left

    return y[left] * w_left[:, None] + y[right] * w_right[:, None]

new_pe = interp(mx.arange(128)/127, old_pe)
```
