### ISSUE TITLE
[Feature Request] Add Stable LM 2 1.6B Lora or QLora example

### ISSUE THREAD

**Issue by madroidmaq** [ml-explore/mlx-examples#356]
Recently, Stability.AI released a 1.6B small model, which is of great significance for mobile deployment. It is expected that examples of corresponding fine-tuning (Lora&QLora) can be added.

When I try to convert the `stabilityai/stablelm-2-zephyr-1_6b` model, I encountered a problem with `ValueError: Model type stablelm_epoch not supported.`， the details are as follows

```
python convert.py --hf-path stabilityai/stablelm-2-zephyr-1_6b -q
[INFO] Loading
Fetching 5 files: 100%|███████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  8.06it/s]
The repository for stabilityai/stablelm-2-zephyr-1_6b contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/stabilityai/stablelm-2-zephyr-1_6b.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y
A new version of the following files was downloaded from https://huggingface.co/stabilityai/stablelm-2-zephyr-1_6b:
- configuration_stablelm_epoch.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
The repository for stabilityai/stablelm-2-zephyr-1_6b contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/stabilityai/stablelm-2-zephyr-1_6b.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y
tokenization_arcade100k.py: 100%|██████████████████████████████████████████| 9.89k/9.89k [00:00<00:00, 10.9MB/s]
A new version of the following files was downloaded from https://huggingface.co/stabilityai/stablelm-2-zephyr-1_6b:
- tokenization_arcade100k.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
[INFO] Quantizing
ERROR:root:Model type stablelm_epoch not supported.
Traceback (most recent call last):
  File "/Users/madroid/Desktop/mlx-examples/lora/convert.py", line 97, in <module>
    weights, config = quantize(weights, config, args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/madroid/Desktop/mlx-examples/lora/convert.py", line 16, in quantize
    model_class, model_args_class = utils._get_classes(config=config)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/madroid/Desktop/mlx-examples/lora/utils.py", line 40, in _get_classes
    raise ValueError(msg)
ValueError: Model type stablelm_epoch not supported.
``` 

Here are some model performance and detailed information:
![image](https://github.com/ml-explore/mlx-examples/assets/6247142/70ac5257-1e50-4e26-873e-934ae5fd2a9e)

- [introducing-stable-lm-2](https://stability.ai/news/introducing-stable-lm-2)
- [stabilityai/stablelm-2-1_6b](https://huggingface.co/stabilityai/stablelm-2-1_6b)
- [stabilityai/stablelm-2-zephyr-1_6b](https://huggingface.co/stabilityai/stablelm-2-zephyr-1_6b)

**Comment by madroidmaq** [comment]
The Stable LM model can now be fine-tuned using mlx_lm.lora, close this task.
