### ISSUE TITLE
Cannot execute mnist after installation

### ISSUE THREAD

**Issue by jkeshet** [ml-explore/mlx-examples#410]
I succesfully installed mlx (conda). I am trying now to execute mnist example. So I started by running "pip install -r requirements.txt"

```
pip install -r requirements.txt
Requirement already satisfied: mlx in /Users/jkeshet/Packages/anaconda3/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (0.1.0)
Requirement already satisfied: numpy in /Users/jkeshet/Packages/anaconda3/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (1.23.5)
```

Then I get an error when importing:
```
python
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:53:08)
[Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mlx
>>> mport mlx.core as mx
  File "<stdin>", line 1
    mport mlx.core as mx
          ^
SyntaxError: invalid syntax
>>> import mlx.core as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/jkeshet/Packages/anaconda3/lib/python3.9/site-packages/mlx/core.cpython-39-darwin.so, 0x0002): Symbol not found: __ZN3mlx4core8allcloseERKNS0_5arrayES3_ddNSt3__17variantIJNS4_9monostateENS0_6StreamENS0_6DeviceEEEE
  Referenced from: <CCAFD20B-13A2-3BF1-A9A8-751D3E051203> /Users/jkeshet/Packages/anaconda3/lib/python3.9/site-packages/mlx/core.cpython-39-darwin.so
  Expected in:     <D83A5AC9-E2AA-3FFB-A874-54D035F2C263> /Users/jkeshet/Packages/anaconda3/lib/python3.9/site-packages/mlx/lib/libmlx.dylib
>>>
```

**Comment by awni** [comment]
What is you MacOS and hardware?

**Comment by jkeshet** [comment]
Macbook Pro 14" / Apple M1 Pro / 32 GB / OS 14.2.1 (23C71)

**Comment by awni** [comment]
Could you try installing MLX via pip? E.g. `conda remove mlx` and `pip install mlx`.. just want to be sure the conda dist is not causing problems.

Your hardware and OS should be good. Let's also be sure you are not building for x86:

`python -c "import platform; print(platform.processor())"` should say `arm`

**Comment by jkeshet** [comment]
I uninstalled and installed anaconda from scratch. Now it works. Thanks!!
