### ISSUE TITLE
Saved checkpoints are overwritten by the final model / following checkpoints

### ISSUE THREAD

**Issue by yukiarimo** [ml-explore/mlx-examples#430]
How to make checkpoints on every 25 steps save each to a directory like `/checkpoint/iter_num_adapters.npz` instead of overwriting everything into `adapters.npz`

**Comment by ivanfioravanti** [comment]
@awni  I'll fix this one. There is also a bug that save adapters only after eval counter is reached.

**Comment by yukiarimo** [comment]
Hey, I see that you've changed something. But it is still not working. I'm worried about this particular file that I was using: https://github.com/ml-explore/mlx-examples/blob/main/lora/lora.py

It's the same!

**Comment by awni** [comment]
Ah the update was to MLX LM, which you should use for more feature rich fine-tuning: [docs here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md).

The basic Lora example is not going to change much from here on out in the interest of keeping it simple / educational / hackable.

**Comment by yukiarimo** [comment]
Also, will the save fusing method and GGUFing work for that approach?

**Comment by awni** [comment]
Although you are right, the help is broken :(

```
python -m mlx_lm.lora --help
Traceback (most recent call last):
  File "/Users/awnihannun/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/awnihannun/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/awnihannun/repos/mlx-examples/llms/mlx_lm/lora.py", line 6, in <module>
    import mlx.optimizers as optim
  File "/Users/awnihannun/repos/mlx/python/mlx/optimizers/__init__.py", line 3, in <module>
    from mlx.optimizers.optimizers import *
  File "/Users/awnihannun/repos/mlx/python/mlx/optimizers/optimizers.py", line 10, in <module>
    class Optimizer:
  File "/Users/awnihannun/repos/mlx/python/mlx/optimizers/optimizers.py", line 123, in Optimizer
    def _maybe_schedule(self, name: str, param : Union[Callable, Any]):
NameError: name 'Any' is not defined
```

**Comment by awni** [comment]
Basically: `pip install mlx-lm`

Then:

```shell
python -m mlx_lm.lora --help            
usage: lora.py [-h] [--model MODEL] [--max-tokens MAX_TOKENS] [--temp TEMP]
               [--prompt PROMPT] [--train] [--data DATA]
               [--lora-layers LORA_LAYERS] [--batch-size BATCH_SIZE]
               [--iters ITERS] [--val-batches VAL_BATCHES]
               [--learning-rate LEARNING_RATE]
               [--steps-per-report STEPS_PER_REPORT]
               [--steps-per-eval STEPS_PER_EVAL]
               [--resume-adapter-file RESUME_ADAPTER_FILE]
               [--adapter-file ADAPTER_FILE] [--save-every SAVE_EVERY]
               [--test] [--test-batches TEST_BATCHES]
               [--max_seq_length MAX_SEQ_LENGTH] [--seed SEED]

LoRA or QLoRA finetuning.

options:
  -h, --help            show this help message and exit
  --model MODEL         The path to the local model directory or Hugging Face
                        repo.
  --max-tokens MAX_TOKENS, -m MAX_TOKENS
                        The maximum number of tokens to generate
  --temp TEMP           The sampling temperature
  --prompt PROMPT, -p PROMPT
                        The prompt for generation
  --train               Do training
  --data DATA           Directory with {train, valid, test}.jsonl files
  --lora-layers LORA_LAYERS
                        Number of layers to fine-tune
  --batch-size BATCH_SIZE
                        Minibatch size.
  --iters ITERS         Iterations to train for.
  --val-batches VAL_BATCHES
                        Number of validation batches, -1 uses the entire
                        validation set.
  --learning-rate LEARNING_RATE
                        Adam learning rate.
  --steps-per-report STEPS_PER_REPORT
                        Number of training steps between loss reporting.
  --steps-per-eval STEPS_PER_EVAL
                        Number of training steps between validations.
  --resume-adapter-file RESUME_ADAPTER_FILE
                        Load path to resume training with the given adapter
                        weights.
  --adapter-file ADAPTER_FILE
                        Save/load path for the trained adapter weights.
  --save-every SAVE_EVERY
                        Save the model every N iterations.
  --test                Evaluate on the test set after training
  --test-batches TEST_BATCHES
                        Number of test set batches, -1 uses the entire test
                        set.
  --max_seq_length MAX_SEQ_LENGTH
                        Maximum sequence length.
  --seed SEED           The PRNG seed
```

**Comment by yukiarimo** [comment]
I see. Thanks, I’ll check it later!
