### ISSUE TITLE
image2image.py broken

### ISSUE THREAD

**Issue by iLoveBug** [ml-explore/mlx-examples#440]
using mlx 0.2.0, and the following command:
python image2image.py --strength 0.5 ~/Downloads/3111706926308_.pic.jpg 'a dragon on the sea'

I got the error:

Traceback (most recent call last):
  File "/Users/zhangfan/Documents/AI/mlx-examples/stable_diffusion/image2image.py", line 44, in <module>
    for x_t in tqdm(latents, total=int(args.steps * args.strength)):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/Users/zhangfan/Documents/AI/mlx-examples/stable_diffusion/stable_diffusion/__init__.py", line 148, in generate_latents_from_image
    x_0 = mx.broadcast_to(x_0, [n_images] + x_0.shape[1:])
                               ~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate list (not "tuple") to list

any one got the same problem?

**Comment by awni** [comment]
Sorry, that was probably broken when we changed the shape to tuple. I will send a fix.
