### ISSUE TITLE
Failing test on whisper

### ISSUE THREAD

**Issue by xymz** [ml-explore/mlx-examples#444]
Almost same with https://github.com/ml-explore/mlx-examples/issues/395 . And my environment is also same(M3). 

```bash
/Users/user/projects/mlx-examples/env/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
.........F.
======================================================================
FAIL: test_transcribe_alice (__main__.TestWhisper)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/user/projects/mlx-examples/whisper/test.py", line 312, in test_transcribe_alice
    check_segment(result["segments"][73], expected_73)
  File "/Users/user/projects/mlx-examples/whisper/test.py", line 306, in check_segment
    self.assertAlmostEqual(seg[k], v, places=2)
AssertionError: 0.009059515781700611 != 0.002246702555567026 within 2 places (0.006812813226133585 difference)

----------------------------------------------------------------------
Ran 11 tests in 17.714s

FAILED (failures=1)
```

But this is a quite bigger difference than expected.

**Comment by awni** [comment]
Whisper tests should be passing now.
