### ISSUE TITLE
homebred v conda: cannot build cifar example

### ISSUE THREAD

**Issue by jrp2014** [ml-explore/mlx-examples#447]
The instructions need to be a little more explicit about build environments.

I used the brew instructions in the mlx-data repo to build that library.

When I cd here to cigar, `pip install -r requirements` and then ` python main.py`, I get

```
Traceback (most recent call last):
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/cifar/main.py", line 9, in <module>
    from dataset import get_cifar10
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/cifar/dataset.py", line 2, in <module>
    from mlx.data.datasets import load_cifar10
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx/data/__init__.py", line 4, in <module>
    from ._c import *
ImportError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx/data/_c.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libturbojpeg.0.dylib
  Referenced from: <45731254-2CFD-3037-B5FF-ECAA0087722C> /opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx/data/_c.cpython-312-darwin.so
  Reason: tried: '/opt/homebrew/Caskroom/miniconda/base/envs/mlx/bin/../lib/libturbojpeg.0.dylib' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/mlx/bin/../lib/libturbojpeg.0.dylib' (no such file)
```
I thought that condo, etc, was supposed to prevent this sort of thing from happening.  What am I doing wrong, please?  Could the instructions be made a bit more fulsome?

**Comment by awni** [comment]
Can you try `pip install -U mlx-data` and then 

```
python -c "from mlx.data.datasets import load_cifar10"
```

**Comment by jrp2014** [comment]
That worked.  Thanks.  Maybe I was using the mlx data that I had built locally.  And the cigar example works.

```
...
Epoch 00 [080] | Train loss 1.609 | Train acc 0.410 | Throughput: 2588.24 images/second
Epoch 00 [090] | Train loss 1.580 | Train acc 0.359 | Throughput: 2588.09 images/second
Epoch 00 [100] | Train loss 1.635 | Train acc 0.398 | Throughput: 2557.45 images/second
Epoch 00 [110] | Train loss 1.408 | Train acc 0.488 | Throughput: 2566.57 images/second
Epoch 00 [120] | Train loss 1.410 | Train acc 0.500 | Throughput: 2580.58 images/second
Epoch 00 [130] | Train loss 1.477 | Train acc 0.438 | Throughput: 2565.19 images/second
Epoch 00 [140] | Train loss 1.396 | Train acc 0.488 | Throughput: 2588.39 images/second
Epoch 00 [150] | Train loss 1.426 | Train acc 0.449 | Throughput: 2577.05 images/second
Epoch 00 [160] | Train loss 1.430 | Train acc 0.488 | Throughput: 2562.38 images/second
Epoch 00 [170] | Train loss 1.370 | Train acc 0.484 | Throughput: 2587.62 images/second
Epoch 00 [180] | Train loss 1.362 | Train acc 0.480 | Throughput: 2595.86 images/second
Epoch 00 [190] | Train loss 1.154 | Train acc 0.590 | Throughput: 2579.88 images/second
...
```
If you understand what was happening, perhaps the installation from source documentation could be updated.

**Comment by jrp2014** [comment]
Wow.  mlx seems to be getting faster:
```
Epoch 01 [010] | Train loss 1.266 | Train acc 0.539 | Throughput: 4963.58 images/second
Epoch 01 [020] | Train loss 1.248 | Train acc 0.555 | Throughput: 4992.35 images/second
Epoch 01 [030] | Train loss 1.335 | Train acc 0.484 | Throughput: 4811.33 images/second
Epoch 01 [040] | Train loss 1.363 | Train acc 0.535 | Throughput: 4922.65 images/second
Epoch 01 [050] | Train loss 1.364 | Train acc 0.484 | Throughput: 4850.03 images/second
Epoch 01 [060] | Train loss 1.179 | Train acc 0.570 | Throughput: 4912.40 images/second
Epoch 01 [070] | Train loss 1.214 | Train acc 0.598 | Throughput: 4818.70 images/second
Epoch 01 [080] | Train loss 1.174 | Train acc 0.590 | Throughput: 4917.31 images/second
Epoch 01 [090] | Train loss 1.152 | Train acc 0.586 | Throughput: 4900.87 images/second
Epoch 01 [100] | Train loss 1.167 | Train acc 0.566 | Throughput: 4939.23 images/second
Epoch 01 [110] | Train loss 1.102 | Train acc 0.570 | Throughput: 4930.13 images/second
Epoch 01 [120] | Train loss 1.100 | Train acc 0.625 | Throughput: 4845.19 images/second
Epoch 01 [130] | Train loss 1.178 | Train acc 0.594 | Throughput: 4858.89 images/second
Epoch 01 [140] | Train loss 1.052 | Train acc 0.590 | Throughput: 4864.82 images/second
```

**Comment by awni** [comment]
More to come!
