### ISSUE TITLE
unable to run mixtral

### ISSUE THREAD

**Issue by jbrodriguez** [ml-explore/mlx-examples#465]
i'm getting the following error

```
~/tmp/mlx-examples/llms/mixtral main* 5m
❯ python3 mixtral.py --model-path mlx_model
[INFO] Loading model from disk.
[INFO] Starting generation...
In the beginning the Universe was created.Traceback (most recent call last):
  File "<redacted>/tmp/mlx-examples/llms/mixtral/mixtral.py", line 324, in <module>
    for token, _ in zip(generate(prompt, model, args.temp), range(args.max_tokens)):
  File "<redacted>/tmp/mlx-examples/llms/mixtral/mixtral.py", line 275, in generate
    logits, cache = model(prompt[None])
                    ^^^^^^^^^^^^^^^^^^^
  File "<redacted>/tmp/mlx-examples/llms/mixtral/mixtral.py", line 213, in __call__
    h, cache[e] = layer(h, mask, cache[e])
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted>/tmp/mlx-examples/llms/mixtral/mixtral.py", line 177, in __call__
    r, cache = self.attention(self.attention_norm(x), mask, cache)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted>/tmp/mlx-examples/llms/mixtral/mixtral.py", line 106, in __call__
    queries = self.rope(queries)
              ^^^^^^^^^^^^^^^^^^
  File "<redacted>/tmp/mlx-examples/llms/mixtral/mixtral.py", line 51, in __call__
    costheta, sintheta = RoPE.create_cos_sin_theta(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'RoPE' has no attribute 'create_cos_sin_theta'
```

these are the contents of my mlx_model folder

```
❯ l mlx_model/
.rw-r--r--  354 <redacted> staff 20 Feb 12:06 -N config.json
.rw-r--r-- 493k <redacted> staff 20 Feb 12:01 -N tokenizer.model
.rw-r--r-- 3.6G <redacted> staff 20 Feb 12:01 -N weights.0.npz
.rw-r--r-- 3.6G <redacted> staff 20 Feb 12:02 -N weights.1.npz
.rw-r--r-- 3.6G <redacted> staff 20 Feb 12:02 -N weights.2.npz
.rw-r--r-- 3.6G <redacted> staff 20 Feb 12:03 -N weights.3.npz
.rw-r--r-- 3.6G <redacted> staff 20 Feb 12:04 -N weights.4.npz
.rw-r--r-- 3.6G <redacted> staff 20 Feb 12:04 -N weights.5.npz
.rw-r--r-- 3.6G <redacted> staff 20 Feb 12:05 -N weights.6.npz
.rw-r--r-- 3.6G <redacted> staff 20 Feb 12:06 -N weights.7.npz
```

i've searched for `create_cos_sin_theta` both in the examples and in the mlx framework code and i can't find it 🤷‍♂️

**Comment by angeloskath** [comment]
Yeah that is a bug introduced when we switched RoPE to the fast implementation. No need for creating cos and sin theta anymore.

I would advise using the default RoPE and passing the base as a parameter since it is now supported. If you do fix this feel free to PR it, we would appreciate the fix, otherwise we 'll get to it shortly.

**Comment by awni** [comment]
@jbrodriguez let us know if you are working on this, ow I will send a fix later today.

**Comment by ivanfioravanti** [comment]
Please check PR @angeloskath and @awni is it ok?

**Comment by jbrodriguez** [comment]
i was worked on it https://github.com/ml-explore/mlx-examples/pull/470, but someone beat me to it :)

**Comment by ivanfioravanti** [comment]
Merge the @jbrodriguez PR 💪

**Comment by angeloskath** [comment]
Love the chivalry and attitude from both of you guys!!!

**Comment by angeloskath** [comment]
Closing since @jbrodriguez fixed it at #470 .
