### ISSUE TITLE
Running python -m mlx_lm.fuse - Resulting in this error: IndexError: list index out of range

### ISSUE THREAD

**Issue by nkotak** [ml-explore/mlx-examples#508]
I fine-tuned a LoRA and tried to fuse the adapter back into the model. but for some reason I'm getting thrown this error. The model is a 7B parameter merge model which I converted to MLX and the Lora was trained on 16 layers. 

I tried another LoRA I fine tuned on 32 layers and I ran into the same issue. Wondering if I can receive some help here?

Thank you!

```
user@MacBook-Pro mlx-examples % python -m mlx_lm.fuse --model /Users/user/AI/mergekit/Koti-Dare-Ties-v1.0-MLX --adapter-file /Users/user/AI/mlx-examples/checkpoints/2400_adapters.npz --save-path /Users/user/AI/mergekit/
Loading pretrained model
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/mlx_lm/fuse.py", line 105, in <module>
    main()
  File "/opt/homebrew/lib/python3.11/site-packages/mlx_lm/fuse.py", line 61, in main
    model = apply_lora_layers(model, args.adapter_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mlx_lm/tuner/utils.py", line 88, in apply_lora_layers
    model.update_modules(tree_unflatten(linear_replacements))
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 395, in update_modules
    apply(self, modules)
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 385, in apply
    apply(current_value, new_value)
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 385, in apply
    apply(current_value, new_value)
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 389, in apply
    new_value = modules[i]
                ~~~~~~~^^^
IndexError: list index out of range
```

**Comment by nkotak** [comment]
I think I was trying to fuse the model with a different model with different parameters. So im going to close this!

**Comment by awni** [comment]
Glad you were able to solve it!
