### ISSUE TITLE
Qwen2: Received parameters not in model: lm_head.weight

### ISSUE THREAD

**Issue by madroidmaq** [ml-explore/mlx-examples#564]
对  `Qwen/Qwen1.5-0.5B-Chat` 进行微调，报错信息如下：

```
Loading pretrained model
Fetching 6 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 20832.64it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/madroid/develop/workspace/mlx-examples/llms/mlx_lm/lora2.py", line 164, in <module>
    model, tokenizer = load(args.model)
                       ^^^^^^^^^^^^^^^^
  File "/Users/madroid/develop/workspace/mlx-examples/llms/mlx_lm/utils.py", line 385, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/madroid/develop/workspace/mlx-examples/llms/mlx_lm/utils.py", line 349, in load_model
    model.load_weights(list(weights.items()))
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 203, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: lm_head.weight.
```

我怀疑是 https://github.com/ml-explore/mlx-examples/pull/544 提交引入的问题，我 revert 对应提交之后再次运行，他就可以正常工作了。

**Comment by mzbac** [comment]
Maybe we need to be smarter to handle the `tie_word_embeddings` configuration. It seems that qwen2 enabled the tie_word_embeddings but also provided lm_head.

**Comment by mzbac** [comment]
A potential solution would be to always initialize the lm_head and, based on whether tie_word_embeddings is enabled or not, copy the weight from token embed to lm_head during load weights. Double-check that qwen2 0.5B pretty much copies the embedding to lm_head.
```
import glob
from mlx_lm.utils import get_model_path, load_model
import mlx.core as mx

model_path = get_model_path("Qwen/Qwen1.5-0.5B-Chat")

weight_files = glob.glob(str(model_path / "*.safetensors"))

weights = {}
for wf in weight_files:
    weights.update(mx.load(wf))

print(
    mx.allclose(
        weights["model.embed_tokens.weight"], weights["lm_head.weight"], atol=1e-5
    )
)

# Output: array(True, dtype=bool)
```

**Comment by awni** [comment]
> A potential solution would be to always initialize the lm_head

A challenge there is that we load the weights in strict mode so if the `lm_head.weight` is missing then it will raise an error.

Another is to use something like a [`sanitize_weights`](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/models/llama.py#L182-L187) which we already check for when loading the model. It would probably need to change to be a class method so it could check `self.args`.

**Comment by mzbac** [comment]
> > A potential solution would be to always initialize the lm_head
> 
> A challenge there is that we load the weights in strict mode so if the `lm_head.weight` is missing then it will raise an error.
> 
> Another option is to use something like a [`sanitize_weights`](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/models/llama.py#L182-L187) which we already check for when loading the model. It would probably need to change to be a class method so it could check `self.args`.

Yeah, I was thinking the same solution. I wasn't sure about changing sanitize to a class method vs creating a new method in utils for checking tie and clone weight. If you are happy to change sanitize to the class method and do weight clone that, I am happy to work on the PR for that.

**Comment by awni** [comment]
I'm okay with that...seems like a small delta and I don't think we lose much from moving it to be a instance method.
