### ISSUE TITLE
LoRA: Increased volatility of train loss

### ISSUE THREAD

**Issue by madroidmaq** [ml-explore/mlx-examples#583]
When using the latest LoRA training, the volatility of Loss became larger. When I further analyzed the cause, I suspected that it might have been introduced by commit #528 due to an internal reordering of the dataset.

https://github.com/ml-explore/mlx-examples/blob/e2205beb668abb2334a75f405de094436cd323fe/llms/mlx_lm/tuner/trainer.py#L78-L86

I revert this commit and retrain, and the loss curve returns to stability. The following is the situation during my training. The fluctuation in this part will reduce the accuracy of the final model by about 10%.

<img width="1343" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/6247142/ee815c6f-edf9-4d02-a18b-119e8fcfdff1">

I'm not quite sure what the reason for this adjustment is, or how I should ignore this part of the logic for sorting the dataset in this case. If this part of the logic is really needed, the way I think of it is to enlarge it in the Dataset definition and allow adding your own data sets.

**Comment by madroidmaq** [comment]
I used a private data set for training, with a data set ratio of 8:1:1, and a total of about 10k. In the scenario I trained, the model would have a stable output (a structured URL instruction), so it was easy for me to calculate its accuracy.

Accuracy before changes: 51.98% (551/1060)
Accuracy after changes: 41.60% (441/1060)

**Comment by awni** [comment]
Yikes that’s pretty bad. So couple ideas:

1. we can have a no sort flag
2. Could try to make batch content more random. 
3. could revert the sorting for the time being

I will play around with some options. If you have time to explore a bit that would also be helpful!

**Comment by madroidmaq** [comment]
> Yikes that’s pretty bad. So couple ideas:
> 
> 1. we can have a no sort flag
> 2. Could try to make batch content more random.
> 3. could revert the sorting for the time being
> 
> I will play around with some options. If you have time to explore a bit that would also be helpful!

I'd be happy to take a stab at this section and test it if you have some changes to make.

1. adding sort flag is a quick solution.
2. disrupting the dataset is also a good idea, I had a try on this part and there was roughly 1% accuracy improvement (52.877% -> 53.774%).


In addition to that, I'd like to know what you think of this part of the dataset formatting change (#548), and whether this part of the submission is something that will be accepted (or whether it's simple) in your opinion.
After I merge this part (and of course, not necessarily relying on this part of the tweak), I'll try to reproduce the training approach in the paper [Rethinking Optimization and Architecture for Tiny Language Models](https://huggingface.co/papers/2402.02791)
, dynamically adjusting the learning rate as well as the batch sizes when fine-tuning. My current idea of how to dynamically adjust the batch size is based on the dataset, as it can be decoupled from the rest of the fine-tuning.

**Comment by awni** [comment]
Thanks!! I will take a look at #548 shortly, sorry for the delay!

**Comment by awni** [comment]
@madroidmaq did you have any time to investigate this? I am hoping to come back to it and figure out a better batching strategy.

**Comment by madroidmaq** [comment]
@awni  Synchronizing some of my recent attempts, so far the logic for sorting has been the least effective, other than that I've tried random sorting and sorting by label (I have the corresponding lebel information in my data).

Here is some data from my tests, the final accuracy and the loss curve.


| Header | Header |
|--------|--------|
| <img width="400" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/6247142/9be89a10-c610-4537-a346-f1d58da9035a"> |  <img width="400" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/6247142/8104fe5e-443c-4699-9b8b-f676ed855502"> |

I don't have any other validation optimization ideas on my side, I can submit the local logic for adding the sort flag to PR first, and then tweak it if there are other better ways to deal with it in the future.

**Comment by awni** [comment]
Thanks for the update.. it might be best to simply disable sorting and compile in LoRA for now :(. It is a modest but nice speed improvement so it's a shame, but it clearly requires some more work to get right.

**Comment by madroidmaq** [comment]
Synchronizing with the bad news, I rebase the latest code and test it and find that the loss curve changes similarly to the previous one, and the way we I used the flag is indeed working. However, when I tested the accuracy, I found that there was a significant drop in both sets of data, and the difference between the 2 became very small. I'm not quite sure what's causing this at the moment, and I'll further rule out recent code commits as having an effect on this.

The dashed line shows the training results of the code before rebase, and the solid lines show the results of passing in true and False via flag.

![image](https://github.com/ml-explore/mlx-examples/assets/6247142/26045392-8278-4a36-93ca-0b7f5532813c)


Accuracy also dropped from 54% to around 18%.
![image](https://github.com/ml-explore/mlx-examples/assets/6247142/599d2441-b737-4b09-a132-e2991773b813)

**Comment by awni** [comment]
That doesn't look so good. What version of MLX are you using and what commit for MLX LM?

**Comment by awni** [comment]
@madroidmaq make sure you are using the latest MLX (0.8 or building from source). That's pretty important otherwise you will go through a bad path for RMS Norm (it won't accumulate in the right precision).

**Comment by angeloskath** [comment]
@madroidmaq a couple of weeks ago we changed the default dropout from 0.05 to 0. Could this be the issue?

I am trying to reconcile in the lower training and validation loss with the worse accuracy... Perhaps resetting it to 0.05 in your training config would be something to check.

**Comment by madroidmaq** [comment]
@awni I've tried this with both versions 0.6 and 0.8 of MLX and it works about the same, neither is good. I'm using the most current commit [fbed720](https://github.com/ml-explore/mlx-examples/commit/fbed720d6f9ac7c854c1fdd8d9954fa1ba47691c)。

@angeloskath I'll adjust the dropout to 0.05 and try again.

**Comment by madroidmaq** [comment]
After adjusting the dropout to a value other than 0, the checkpoints file cannot be saved properly, and the following error message is reported:

```
Iter 200: Train loss 1.258, Learning Rate 8.500e-06, It/sec 2.376, Tokens/sec 2526.571, Trained Tokens 220420, Peak mem 9.175 GB
Iter 200: Val loss 1.337, Val took 9.117s
Iter 200: Saved adapter weights to build/checkpoints/200_adapters.npz.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/madroid/develop/workspace/mlx-examples/llms/mlx_lm/lora2.py", line 227, in <module>
    train(
  File "/Users/madroid/develop/workspace/mlx-examples/llms/mlx_lm/tuner/trainer.py", line 320, in train
    lvalue, toks = step(batch)
                   ^^^^^^^^^^^
IndexError: unordered_map::at: key not found
```

I don't know much about this part, should I if I solve this problem, can you provide some ideas that I can try further.

**Comment by awni** [comment]
Oof sorry that’s the compile, you can just remove it for now as in #608

**Comment by angeloskath** [comment]
Hm that is interesting because I just trained with `Dropout` enabled. I assume this means you are not on `main` or on `fast_rms` on top of `mlx-examples`.

**Comment by madroidmaq** [comment]
After I followed the tweaks in #608, it works fine. I tried the dropout parameter and it did improve, but not to the original accuracy. Here are the numbers with the dropout adjusted to 0.05 and 0.1 respectively:

<img width="803" alt="image" src="https://github.com/ml-explore/mlx-examples/assets/6247142/861046cb-3a91-4533-8a9c-22486ca245d9">

In addition to that, I rolled back the code to before #528 was committed and the accuracy was also around 30%. So it's possible that there's something wrong with my local code, and I'll look into it further. Currently my code logic is somewhat coupled with the code in the project, I'll spend some time decoupling them, and will probably also follow up with tweaks to the APIs in the current project so that refactoring can go smoothly.

But this shouldn't affect commit #611 on sort flag.
