### ISSUE TITLE
https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/SERVER.md example is broken

### ISSUE THREAD

**Issue by jrwren** [ml-explore/mlx-examples#612]
Following https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/SERVER.md exactly yields:

```
127.0.0.1 - - [24/Mar/2024 13:38:05] "POST /v1/chat/completions HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 54645)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/lib/python3.11/site-packages/mlx_lm/server.py", line 85, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/opt/homebrew/lib/python3.11/site-packages/mlx_lm/server.py", line 155, in do_POST
    method(prompt, stop_id_sequences)
  File "/opt/homebrew/lib/python3.11/site-packages/mlx_lm/server.py", line 242, in handle_completion
    for (token, _), _ in zip(
  File "/opt/homebrew/lib/python3.11/site-packages/mlx_lm/utils.py", line 190, in generate_step
    logits = apply_repetition_penalty(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mlx_lm/utils.py", line 112, in apply_repetition_penalty
    logits[:, indices] = selected_logits
    ~~~~~~^^^^^^^^^^^^
ValueError: Cannot broadcast array of shape (14) into shape (14,1).
----------------------------------------
curl: (52) Empty reply from server

```

**Comment by awni** [comment]
Sorry this should be fixed with the latest (pre release) MLX. We'll get a release out asap.

**Comment by rshah918** [comment]
Haha I was just about to post an issue on this... Thanks @awni !!!! Appreciate you

**Comment by awni** [comment]
We are pushing a patch release to pypi right now. If you do:

pip install -U mlx

in a few minutes you should get a working version. Let me know if you still have any issues.
