### ISSUE TITLE
Can't finetune mixtral-8x7B base model

### ISSUE THREAD

**Issue by lin72h** [ml-explore/mlx-examples#615]
Hi team,

Firstly, thanks for this awesome project. I just finetuned a mistral-7b-instruct-v0.2 model with no problem yesterday on my 128GB M3 macbook pro, but today I can't finetune  the Mixtral-8x7B-v0.1 model. Here is the error message:
```
python3 -m mlx_lm.lora --train --model ~/Models/mixtral-q4 --data ~/Data/mlx-examples/lora/data --batch-size 2 --lora-layers 16 --iters 3200 --save-every 1000  --learning-rate 1e-4 --adapter-file ~/Models/mixtral-ft                        
/Users/linz/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Loading pretrained model
Trainable parameters: 0.005% (2.229M/46702.793M)
Loading datasets
Training
Starting training..., iters: 3200
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/lora.py", line 257, in <module>
    run(types.SimpleNamespace(**args))
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/lora.py", line 204, in run
    train(
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/tuner/trainer.py", line 219, in train
    lvalue, toks = step(batch)
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/tuner/trainer.py", line 195, in step
    (lvalue, toks), grad = loss_value_and_grad(model, *batch)
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx/nn/utils.py", line 34, in wrapped_value_grad_fn
    value, grad = value_grad_fn(model.trainable_parameters(), *args, **kwargs)
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx/nn/utils.py", line 28, in inner_fn
    return fn(*args, **kwargs)
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/tuner/trainer.py", line 67, in default_loss
    logits, _ = model(inputs)
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/models/mixtral.py", line 238, in __call__
    out, cache = self.model(inputs, cache)
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/models/mixtral.py", line 221, in __call__
    h, cache[e] = layer(h, mask, cache[e])
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/models/mixtral.py", line 187, in __call__
    r = self.block_sparse_moe(self.post_attention_layernorm(h))
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/models/mixtral.py", line 147, in __call__
    mx.eval(inds)
ValueError: [eval] Attempting to eval an array without a primitive.
```

Thanks

**Comment by mzbac** [comment]
Which version of the MLX are you using? There is a new version, 0.8.1, that has just been released. Would you try updating it to see if it fixes the issue?

**Comment by lin72h** [comment]
@mzbac Thanks for the quick reply, I'm using the pip to install mlx-lm 0.4.0 package, I don't know to do update the mlx to 0.8.1

**Comment by mzbac** [comment]
@lin72h, that will be fixed after the release of https://github.com/ml-explore/mlx-examples/pull/608. In the meantime, you can manually remove the compile in the trainer's step or install mlx-lm from the main branch of mlx-examples.

**Comment by lin72h** [comment]
@mzbac OMG! it works, thanks for the tip! you rock!

**Comment by awni** [comment]
FYI updated MLX LM so you can `pip install -U mlx-lm` to get #608
