### ISSUE TITLE
No attribute 'state' issue when fine-tune with lora.

### ISSUE THREAD

**Issue by 592319702** [ml-explore/mlx-examples#616]
I'm in the folder `./mlx-examples/llms` and run the fine tune command as the instruction (https://github.com/ml-explore/mlx-examples/blob/5a52899405ee911ce07ca3132e781ce149acd6b5/llms/mlx_lm/LORA.md).

But there is the no attribute 'state' issue as following,

```
(mlx) I542464@DY4GPKX1J0 llms % python -m mlx_lm.lora \
    --model mistralai/Mistral-7B-v0.1 \
    --train \
    --batch-size 1 \
    --lora-layers 4 \
    --data ../lora/data
```
Loading pretrained model
Fetching 10 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 67541.13it/s]
Trainable parameters: 0.006% (0.426M/7241.732M)
Loading datasets
Training
Starting training..., iters: 1000
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/I542464/mlx-test/mlx-examples/llms/mlx_lm/lora.py", line 257, in <module>
    run(types.SimpleNamespace(**args))
  File "/Users/I542464/mlx-test/mlx-examples/llms/mlx_lm/lora.py", line 204, in run
    train(
  File "/Users/I542464/mlx-test/mlx-examples/llms/mlx_lm/tuner/trainer.py", line 190, in train
    state = [model.state, optimizer.state]
             ^^^^^^^^^^^
  File "/Users/I542464/miniconda3/envs/mlx/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 88, in __getattr__
    raise AttributeError(f"{type(self)!r} has no attribute {key!r}")
AttributeError: <class 'mlx_lm.models.llama.Model'> has no attribute 'state'

**Comment by 592319702** [comment]
Sorry, it was caused my mlx version is too low, when I upgrade the mlx, the issue was fixed. Please close the issue.
