### ISSUE TITLE
Can't generate token with lora adapter

### ISSUE THREAD

**Issue by lin72h** [ml-explore/mlx-examples#619]
Hi Team,
Just solved the[ training problem](https://github.com/ml-explore/mlx-examples/issues/615) last night, but this time I failed to evaluate the the trained lora adapter with the following command
```
 python3 -m mlx_lm.lora --model ~/Models/mixtral-8x7B-v0.1 \
--adapter-file ~/Models/adapters/mixstral-8x7B-ft.npz \
--prompt "table: 1-10015132-16 columns: Player, No., Nationality, Position, Years in Toronto, Schoo/Club Team \
Q: What is terrence ross' nationality \
A:"
```

I got a strange error

`lora.py: error: unrecognized arguments: --prompt table: 1-10015132-16 columns: Player, No., Nationality, Position, Years in Toronto, Schoo/Club Team Q: What is terrence ross' nationality `

also the fuse can't work either

`python3 -m mlx_lm.fuse --model ~/Models/mixtral-8x7B-v0.1 --adapter-file ~/Models/adapters/mixstral-8x7B-ft.npz --save-path ~/Models/mixtral-ft `

```
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/fuse.py", line 9, in <module>
    from .gguf import convert_to_gguf
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/gguf.py", line 24, in <module>
    class HfVocab:
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx_lm/gguf.py", line 26, in HfVocab
    self, fname_tokenizer: Path, fname_added_tokens: Path | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by awni** [comment]
So for the first one you are probably just copying it into terminal incorrectly. Try putting it in a single line:

```
 python3 -m mlx_lm.lora --model ~/Models/mixtral-8x7B-v0.1 --adapter-file ~/Models/adapters/mixstral-8x7B-ft.npz --prompt "table: 1-10015132-16 columns: Player, No., Nationality, Position, Years in Toronto, Schoo/Club Team\nQ: What is terrence ross' nationality\nA:"
```

**Comment by awni** [comment]
> python3 -m mlx_lm.fuse --model ~/Models/mixtral-8x7B-v0.1 --adapter-file ~/Models/adapters/mixstral-8x7B-ft.npz --save-path ~/Models/mixtral-ft 

I can't reproduce the problem you got with the fusion, it runs fine for me. My recommendation is to update you transformers and try again.

`python3 -m pip install -U transformers`

If you still have an issue, please give more steps to reproduce and we can help debug.

**Comment by lin72h** [comment]
> So for the first one you are probably just copying it into terminal incorrectly. Try putting it in a single line:
> 
I just tried to put everything in a single line as your suggested, but still got the same error 

And I've upgraded all the mlx_lm mlx transformers pipe packages

**Comment by lin72h** [comment]
Very strange if i execute the local repo python file directly, it works for mistral-7b model
`$  python3 ~/Code/Js/Py/mlx-examples/lora/lora.py --model ~/Models/mistral-7b-instruct-v0.2 --adapter-file ~/Models/adapters/adapters.npz --prompt "table: 1-10015132-16 columns: Player, No., Nationality, Position, Years in Toronto, Schoo/Club Team\nQ: What is terrence ross' nationality\nA:"`

and it generate the token correctly:
```
Loading pretrained model
Total parameters 7243.436M
Trainable parameters 1.704M
Loading datasets
Generating
table: 1-10015132-16 columns: Player, No., Nationality, Position, Years in Toronto, Schoo/Club Team\nQ: What is terrence ross' nationality\nA:SELECT Nationality FROM 1-10015132-16 WHERE Player = 'Terrence Ross';
```

but the mixtral model generate even stranger error:
` python3 ~/Code/mlx-examples/lora/lora.py --model ~/Models/mixtral-8x7B-v0.1 --adapter-file ~/Models/adapters/mixstral-8x7B-ft.npz --prompt "table: 1-10015132-16 columns: Player, No., Nationality, Position, Years in Toronto, Schoo/Club Team\nQ: What is terrence ross' nationality\nA:"`
Errors:

```
Loading pretrained model
Traceback (most recent call last):
  File "/Users/linz/Code/Js/Py/mlx-examples/lora/lora.py", line 321, in <module>
    model, tokenizer, _ = lora_utils.load(args.model)
  File "/Users/linz/Code/Js/Py/mlx-examples/lora/utils.py", line 140, in load
    model.load_weights(list(weights.items()))
  File "/Users/linz/Library/Python/3.9/lib/python/site-packages/mlx/nn/layers/base.py", line 203, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.27.block_sparse_moe.experts.2.w3.weight model.layers.25.block_sparse_moe.experts.5.w2.weight model.layers.19.block_sparse_moe.experts.4.w3.weight model.layers.0.block_sparse_moe.experts.6.w2.weight model.layers.7.block_sparse_moe.experts.1.w1.weight model.layers.5.block_sparse_moe.experts.1.w1.weight model.layers.3.block_sparse_moe.experts.5.w1.weight model.layers.27.block_sparse_moe.experts.7.w2.weight model.layers.6.block_sparse_moe.experts.5.w1.weight model.layers.3.block_sparse_moe.experts.5.w3.weight model.layers.31.block_sparse_moe.experts.0.w2.weight model.layers.16.block_sparse_moe.experts.2.w1.weight model.layers.16.block_sparse_moe.experts.0.w1.weight model.layers.27.block_sparse_moe.experts.3.w1.weight model.layers.3.block_sparse_moe.experts.6.w3.weight model.layers.12.block_sparse_moe.experts.7.w3.weight model.layers.27.block_sparse_moe.experts.6.w3.weight model.layers.18.block_sparse_moe.experts.5.w1.weight model.layers.29.block_sparse_moe.experts.6.w3.weight model.layers.3.block_sparse_moe.experts.1.w1.weight model.layers.3.block_sparse_moe.experts.3.w3.weight model.layers.29.block_sparse_moe.experts.5.w1.weight model.layers.17.block_sparse_moe.experts.5.w3.weight model.layers.20.block_sparse_moe.experts.4.w2.weight model.layers.3.block_sparse_moe.experts.7.w1.weight model.layers.6.block_sparse_moe.experts.6.w2.weight model.layers.31.block_sparse_moe.experts.4.w3.weight model.layers.1.block_sparse_moe.experts.5.w2.weight model.layers.13.block_sparse_moe.experts.6.w1.weight model.layers.2.block_sparse_moe.experts.4.w2.weight model.layers.29.block_sparse_moe.experts.5.w2.weight model.layers.22.block_sparse_moe.experts.6.w3.weight model.layers.3.block_sparse_moe.experts.4.w2.weight model.layers.13.block_sparse_moe.experts.7.w2.weight model.layers.15.block_sparse_moe.gate.weight model.layers.8.block_sparse_moe.experts.0.w2.weight model.layers.14.block_sparse_moe.experts.2.w2.weight model.layers.18.block_sparse_moe.experts.5.w3.weight model.layers.4.block_sparse_moe.experts.7.w1.weight model.layers.25.block_sparse_moe.experts.0.w2.weight model.layers.1.block_sparse_moe.experts.4.w3.weight model.layers.26.block_sparse_moe.experts.4.w2.weight model.layers.28.block_sparse_moe.experts.0.w1.weight model.layers.25.block_sparse_moe.experts.5.w1.weight model.layers.17.block_sparse_moe.experts.7.w2.weight model.layers.2.block_sparse_moe.experts.3.w1.weight model.layers.0.block_sparse_moe.experts.3.w1.weight model.layers.17.block_sparse_moe.experts.0.w3.weight model.layers.14.block_sparse_moe.gate.weight model.layers.31.block_sparse_moe.experts.6.w1.weight model.layers.8.block_sparse_moe.experts.7.w3.weight model.layers.31.block_sparse_moe.experts.5.w1.weight model.layers.12.block_sparse_moe.experts.6.w1.weight model.layers.28.block_sparse_moe.experts.5.w2.weight model.layers.6.block_sparse_moe.experts.4.w2.weight model.layers.22.block_sparse_moe.experts.4.w1.weight model.layers.10.block_sparse_moe.experts.6.w3.weight model.layers.10.block_sparse_moe.experts.5.w2.weight model.layers.31.block_sparse_moe.experts.0.w1.weight model.layers.13.block_sparse_moe.experts.7.w3.weight model.layers.19.block_sparse_moe.experts.2.w2.weight model.layers.4.block_sparse_moe.experts.7.w2.weight model.layers.18.block_sparse_moe.experts.0.w2.weight model.layers.14.block_sparse_moe.experts.5.w1.weight model.layers.6.block_sparse_moe.experts.0.w3.weight model.layers.30.block_sparse_moe.experts.7.w1.weight model.layers.16.block_sparse_moe.experts.3.w1.weight model.layers.0.block_sparse_moe.experts.4.w2.weight model.layers.5.block_sparse_moe.experts.7.w3.weight 
```

**Comment by mzbac** [comment]
I haven't looked at the details, so I'm not very sure why the generation command was removed from the lora script. However, if I understand correctly, you just want to do text generation with adapters. You should be able to use the generate script instead.
```
python3 -m mlx_lm.generate --model ~/Models/mixtral-8x7B-v0.1 \
--adapter-file ~/Models/adapters/mixstral-8x7B-ft.npz \
--prompt "table: 1-10015132-16 columns: Player, No., Nationality, Position, Years in Toronto, Schoo/Club Team \
Q: What is terrence ross' nationality \
A:"
```

**Comment by lin72h** [comment]
@mzbac i didn't know mlx_lm.generate can apply lora adapter, now it works. but the second fuse example still fail

**Comment by lin72h** [comment]
@mzbac thanks take your time I've just exploring mlx, very exciting

**Comment by mzbac** [comment]
I think I found the issue while copying the code from llama.cpp convert script. I didn't notice that it uses Python 3.10, so the type `Path | None` is not supported by Python 3.8.0. We need to fix the gguf.py script, but in the meantime, you can update your Python runtime to 3.10 which should fix the issue.

**Comment by awni** [comment]
Thanks for the help debugging all this @mzbac, I missed the fact that @lin72h was using `mlx_lm.lora` to do generation. We removed that a while ago in order to simplify code paths / duplication.

**Comment by awni** [comment]
Also @mzbac do you plan to send a fix for the Python version issue?

**Comment by mzbac** [comment]
> Also @mzbac do you plan to send a fix for the Python version issue?

Yeah, I will try to create a PR to fix it. The change should be small, I just have to run some tests.

**Comment by lin72h** [comment]
Thanks for the update,  i wish i could switch to the swift port in the near future, I'm not good at Python stuff

**Comment by lin72h** [comment]
pull your new updates from gguf.py, the fuse.py problem solved too, works like a charm!

Thanks for guys
