### ISSUE TITLE
Unable to load mlx-community/dbrx-instruct-4bit locally for use in QLoRA

### ISSUE THREAD

**Issue by chimezie** [ml-explore/mlx-examples#646]
I received the following traceback after answering `Y` to the prompt for running the custom code.  I'll put this in the HF issue tracker as well as I'm not sure if this is mlx_lm specific or not.

```bash
% python -m mlx_lm.convert --hf-path mlx-community/dbrx-instruct-4bit --mlx-path raw_models/mlx/dbrx
[..snip..]
Do you wish to run the custom code? [y/N] Y
Traceback (most recent call last):
[..snip..]
  File "/path/mlx-examples/llms/mlx_lm/utils.py", line 394, in fetch_from_hub
    config = AutoConfig.from_pretrained(model_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1125, in from_pretrained
    return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/python3.11/site-packages/transformers/configuration_utils.py", line 611, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/python3.11/site-packages/transformers/configuration_utils.py", line 763, in from_dict
    config = cls(**config_dict)
             ^^^^^^^^^^^^^^^^^^
  File "/path/configuration_dbrx.py", line 233, in __init__
    self.attn_config = DbrxAttentionConfig(**attn_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/configuration_dbrx.py", line 48, in __init__
    raise ValueError(f'Found unknown {kwargs=}')
ValueError: Found unknown kwargs={'return_dict': True, 'output_hidden_states': False, 'output_attentions': False, 'torchscript': False, 'torch_dtype': None, 'use_bfloat16': False, 'tf_legacy_loss': False, 'pruned_heads': {}, 'tie_word_embeddings': True, 'chunk_size_feed_forward': 0, 'is_encoder_decoder': False, 'is_decoder': False, 'cross_attention_hidden_size': None, 'add_cross_attention': False, 'tie_encoder_decoder': False, 'max_length': 20, 'min_length': 0, 'do_sample': False, 'early_stopping': False, 'num_beams': 1, 'num_beam_groups': 1, 'diversity_penalty': 0.0, 'temperature': 1.0, 'top_k': 50, 'top_p': 1.0, 'typical_p': 1.0, 'repetition_penalty': 1.0, 'length_penalty': 1.0, 'no_repeat_ngram_size': 0, 'encoder_no_repeat_ngram_size': 0, 'bad_words_ids': None, 'num_return_sequences': 1, 'output_scores': False, 'return_dict_in_generate': False, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'remove_invalid_values': False, 'exponential_decay_length_penalty': None, 'suppress_tokens': None, 'begin_suppress_tokens': None, 'architectures': None, 'finetuning_task': None, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1'}, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'tokenizer_class': None, 'prefix': None, 'bos_token_id': None, 'pad_token_id': None, 'eos_token_id': None, 'sep_token_id': None, 'decoder_start_token_id': None, 'task_specific_params': None, 'problem_type': None, '_name_or_path': ''}
```

**Comment by mzbac** [comment]
It works fine for me on mlx_lm.generate, maybe upgrade to the latest transformers library?

**Comment by chimezie** [comment]
Thanks, I saw the config.json bug you entered on HF.  However, where on my local machine exactly do I copy that file (I'm _assuming_ to the local copy of the downloaded model files)?

**Comment by mzbac** [comment]
It looks like you are trying to convert a quantized model that has already been converted, which may be causing the error. If you just want to re-upload the converted model, you can simply use the HuggingFace cli to do that.

**Comment by chimezie** [comment]
I just wanted to load the quantized model locally and QLoRA train (not convert or generate from it) and used the only command-line option I seem to have for that purpose.  I'll try training with a --model value of 'mlx-community/dbrx-instruct-4bit' directly instead.

**Comment by awni** [comment]
Discussed a bit on discord. Let us know if there is still a problem

**Comment by awni** [comment]
>  I'll try training with a --model value of 'mlx-community/dbrx-instruct-4bit' directly instead.

That's exactly the right thing to do btw. Though tbh you should be able to convert it (which would just be saving to another directory), I'll try and debug what went wrong there.
