### ISSUE TITLE
Failed to convert gemma model.

### ISSUE THREAD

**Issue by danny-su** [ml-explore/mlx-examples#663]
mlx_lm (0.7.0)
mlx (0.9.1)

```bash
python3.11 lora/convert.py --hf-path google/gemma-2b-it --mlx-path /Users/danny/Downloads/llm/data/models/gemma -q
```
```
[INFO] Loading
[INFO] Quantizing
Traceback (most recent call last):
  File "/Users/danny/Downloads/mlx-examples/lora/convert.py", line 95, in <module>
    weights, config = quantize(weights, config, args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danny/Downloads/mlx-examples/lora/convert.py", line 18, in quantize
    model.load_weights(list(weights.items()))
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 214, in load_weights
    raise ValueError(f"Missing parameters: {missing}.")
ValueError: Missing parameters: lm_head.weight.

```

Also, failed to train mlx-community/quantized-gemma-2b-it 
```
python3.11 lora.py --model mlx-community/quantized-gemma-2b-it --train --lora-layers 8 --batch-size 2 --iters 100 
Loading pretrained model
config.json: 100%|██████████████████████████████████████████████████████████| 2.38k/2.38k [00:00<00:00, 12.9MB/s]
tokenizer_config.json: 100%|████████████████████████████████████████████████| 2.15k/2.15k [00:00<00:00, 17.8MB/s]
model.safetensors.index.json: 100%|█████████████████████████████████████████| 29.3k/29.3k [00:00<00:00, 1.30MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████| 636/636 [00:00<00:00, 2.89MB/s]
tokenizer.model: 100%|███████████████████████████████████████████████████████| 4.24M/4.24M [00:06<00:00, 623kB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████| 17.5M/17.5M [00:23<00:00, 746kB/s]
model.safetensors: 100%|████████████████████████████████████████████████████| 2.16G/2.16G [13:19<00:00, 2.71MB/s]
Fetching 7 files: 100%|███████████████████████████████████████████████████████████| 7/7 [13:20<00:00, 114.30s/it]
Traceback (most recent call last):███████████████████████████████████████████| 17.5M/17.5M [00:23<00:00, 769kB/s]
  File "/Users/danny/Downloads/mlx-examples/lora/lora.py", line 321, in <module>
    model, tokenizer, _ = lora_utils.load(args.model)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/danny/Downloads/mlx-examples/lora/utils.py", line 135, in load
    model.load_weights(list(weights.items()))
  File "/opt/homebrew/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 214, in load_weights
    raise ValueError(f"Missing parameters: {missing}.")
ValueError: Missing parameters: lm_head.biases lm_head.scales lm_head.weight.

```

**Comment by mzbac** [comment]
The Lora example only has basic model support for LLama. You may need to use MLX-LM's Lora for more feature-rich functionality.
https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md
