### ISSUE TITLE
Whisper: Using large-v3 instead of tiny model for test fails

### ISSUE THREAD

**Issue by jrp2014** [ml-explore/mlx-examples#678]
Trying the large-v3 model (the original `python test.py` works fine, in about 8s) suggests that there are some hard dependencies on the model used in the test, or there is something wrong.

```python

MODEL_NAME = "large-v3"
MLX_FP32_MODEL_PATH = "mlx_models/large-v3_fp32"
MLX_FP16_MODEL_PATH = "mlx_models/large-v3_fp16"
MLX_4BITS_MODEL_PATH = "mlx_models/large-v3_quantized_4bits"
```
and running python test-large-v3.py produces:
```
(mlx) ➜  whisper git:(main) ✗ python test-large-v3.py
...EE...FFF
======================================================================
ERROR: test_decode_greedy (__main__.TestWhisper.test_decode_greedy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/test-large-v3.py", line 130, in test_decode_greedy
    result = decoding.decode(self.model, self.mels, fp16=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/whisper/decoding.py", line 725, in decode
    result = DecodingTask(model, options).run(mel)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/whisper/decoding.py", line 613, in run
    audio_features: mx.array = self._get_audio_features(mel)  # encoder forward pass
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/whisper/decoding.py", line 548, in _get_audio_features
    audio_features = self.model.encoder(mel)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/whisper/whisper.py", line 141, in __call__
    x = nn.gelu(self.conv1(x))
                ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx/nn/layers/convolution.py", line 65, in __call__
    y = mx.conv1d(x, self.weight, self.stride, self.padding, self.dilation)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [conv] Expect the input channels in the input and weight array to match but got shapes - input: (1,3000,80) and weight: (1280,3,128)

======================================================================
ERROR: test_decode_lang (__main__.TestWhisper.test_decode_lang)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/test-large-v3.py", line 122, in test_decode_lang
    result = decoding.decode(self.model, self.mels, options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/whisper/decoding.py", line 725, in decode
    result = DecodingTask(model, options).run(mel)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/whisper/decoding.py", line 613, in run
    audio_features: mx.array = self._get_audio_features(mel)  # encoder forward pass
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/whisper/decoding.py", line 548, in _get_audio_features
    audio_features = self.model.encoder(mel)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/whisper/whisper.py", line 141, in __call__
    x = nn.gelu(self.conv1(x))
                ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx/nn/layers/convolution.py", line 65, in __call__
    y = mx.conv1d(x, self.weight, self.stride, self.padding, self.dilation)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [conv] Expect the input channels in the input and weight array to match but got shapes - input: (1,3000,80) and weight: (1280,3,128)

======================================================================
FAIL: test_transcribe (__main__.TestWhisper.test_transcribe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/test-large-v3.py", line 194, in test_transcribe
    self.assertEqual(
AssertionError: ' then the good soul openly shouldered the [63 chars]lone' != ' Then the good soul openly sorted the boat[65 chars]one.'
-  then the good soul openly shouldered the burden she had borne so long in secret and bravely trudged on alone
?     -----                   - ----         ^^ --           ^^                                  ^^^
+  Then the good soul openly sorted the boat and she had buoyed so long in secret and bravely stretched on alone.
? +++++                         +        ^^^^^^           + ^ +                               +  ^^^^           +


======================================================================
FAIL: test_transcribe_alice (__main__.TestWhisper.test_transcribe_alice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/test-large-v3.py", line 215, in test_transcribe_alice
    self.assertEqual(len(result["text"]), 10920)
AssertionError: 10821 != 10920

======================================================================
FAIL: test_transcribe_word_level_timestamps_confidence_scores (__main__.TestWhisper.test_transcribe_word_level_timestamps_confidence_scores)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/test-large-v3.py", line 442, in test_transcribe_word_level_timestamps_confidence_scores
    check_words(result["segments"][0]["words"], expected_0)
  File "/Users/jrp/Documents/AI/mlx/mlx-examples/whisper/test-large-v3.py", line 439, in check_words
    self.assertEqual(word[k], v)
AssertionError: ' then' != ' Then'
-  then
?  ^
+  Then
?  ^


----------------------------------------------------------------------
Ran 11 tests in 106.627s

FAILED (failures=3, errors=2)
```

**Comment by awni** [comment]
Yes the tests very much depend on the model.
