### ISSUE TITLE
TypeError: ModelArgs.__init__() missing 5 required positional arguments

### ISSUE THREAD

**Issue by Ovid** [ml-explore/mlx-examples#732]
I'm trying to train `mlx-community/dbrx-instruct-4bit` but am getting the same error as [this closed ticket](https://github.com/ml-explore/mlx-examples/issues/298)

```
python3 lora.py --train --model mlx-community/dbrx-instruct-4bit --data ~/ai/data --batch-size 2 --lora-layers 8 --iters 1000
Loading pretrained model
Fetching 19 files: 100%|████████████████████████████████████████████████████| 19/19 [00:00<00:00, 306506.83it/s]
Traceback (most recent call last):
  File "/Users/ovid/projects/llms/mlx-examples/lora/lora.py", line 321, in <module>
    model, tokenizer, _ = lora_utils.load(args.model)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ovid/projects/llms/mlx-examples/lora/utils.py", line 148, in load
    model_args = models.ModelArgs.from_dict(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ovid/projects/llms/mlx-examples/lora/models.py", line 40, in from_dict
    return cls(
           ^^^^
TypeError: ModelArgs.__init__() missing 5 required positional arguments: 'hidden_size', 'num_hidden_layers', 'intermediate_size', 'num_attention_heads', and 'rms_norm_eps'
```

I have run the following, just to be sure I have the latest:

```
pip install mlx --upgrade
pip install mlx-lm --upgrade
```

**Comment by Ovid** [comment]
Note that I can successfully run [the example prompt with mlx_lm](https://huggingface.co/mlx-community/dbrx-instruct-4bit#example):

```
$ time python -m mlx_lm.generate --model mlx-community/dbrx-instruct-4bit --prompt "Hello" --trust-remote-code --use-default-chat-template --max-tokens 500
... lots of output omitted
```

**Comment by mzbac** [comment]
I think the LORA example only supports limited models, not sure if it will work with dbrx-instruct-4bit. would you try to use mlx_lm.lora instead https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md

**Comment by awni** [comment]
Exactly as @mzbac said. It should work in `mlx_lm.lora`. E.g. `mlx_lm.lora --model  mlx-community/dbrx-instruct-4bit  --train ...`. Let us know if it doesn't and I will re-open.
