### ISSUE TITLE
Convert OpenELM to MLX compatible (ValueError: Unrecognized configuration class_)

### ISSUE THREAD

**Issue by ahmetkca** [ml-explore/mlx-examples#742]
Here is the output:
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[INFO] Loading
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.30k/1.30k [00:00<00:00, 19.1MB/s]
generation_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 2.10MB/s]
configuration_openelm.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14.3k/14.3k [00:00<00:00, 85.0MB/s]
modeling_openelm.py: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39.3k/39.3k [00:00<00:00, 12.2MB/s]
generate_openelm.py: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.45k/7.45k [00:00<00:00, 61.1MB/s]
model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.09G/1.09G [01:29<00:00, 12.1MB/s]
Fetching 6 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [01:30<00:00, 15.01s/it]
The repository for /.cache/huggingface/hub/models--apple--OpenELM-270M/snapshots/0a49ab455190e17fcf02d2f21d15e58f6496c8d9 contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//Users/ahmetkca/.cache/huggingface/hub/models--apple--OpenELM-270M/snapshots/0a49ab455190e17fcf02d2f21d15e58f6496c8d9.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mlx-examples/llms/mlx_lm/main.py", line 20, in <module>
    convert(
  File "/mlx-examples/llms/mlx_lm/.venv/lib/python3.12/site-packages/mlx_lm/utils.py", line 589, in convert
    model, config, tokenizer = fetch_from_hub(model_path, lazy=True)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlx-examples/llms/mlx_lm/.venv/lib/python3.12/site-packages/mlx_lm/utils.py", line 398, in fetch_from_hub
    tokenizer = load_tokenizer(model_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mlx-examples/llms/mlx_lm/.venv/lib/python3.12/site-packages/mlx_lm/tokenizer_utils.py", line 327, in load_tokenizer
    AutoTokenizer.from_pretrained(model_path, **tokenizer_config_extra),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmetkca/Projects/mlx-examples/llms/mlx_lm/.venv/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py", line 890, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.0a49ab455190e17fcf02d2f21d15e58f6496c8d9.configuration_openelm.OpenELMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BarkConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, BrosConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, ClvpConfig, LlamaConfig, CodeGenConfig, CohereConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecAudioConfig, Data2VecTextConfig, DbrxConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FalconConfig, FastSpeech2ConformerConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroundingDinoConfig, GroupViTConfig, HubertConfig, IBertConfig, IdeficsConfig, Idefics2Config, InstructBlipConfig, JambaConfig, JukeboxConfig, Kosmos2Config, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LlavaConfig, LlavaNextConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MambaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MistralConfig, MixtralConfig, MobileBertConfig, MPNetConfig, MptConfig, MraConfig, MT5Config, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OlmoConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, Owlv2Config, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, PersimmonConfig, PhiConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RagConfig, RealmConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, SeamlessM4TConfig, SeamlessM4Tv2Config, SiglipConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, StableLmConfig, Starcoder2Config, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, TvpConfig, UdopConfig, UMT5Config, ViltConfig, VipLlavaConfig, VisualBertConfig, VitsConfig, Wav2Vec2Config, Wav2Vec2BertConfig, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.
```

```python
APPLE_OPENELM_MODELS = [
"OpenELM-270M",
]

if __name__ == "__main__":
    APPLE_HF_ID = "apple"
    MY_HF_ID = "ahmetkca"
    for model in APPLE_OPENELM_MODELS:
        hf_repo_id = f"{APPLE_HF_ID}/{model}"
        upload_hf_repo_id = f"{MY_HF_ID}/{model}"
        convert(
            hf_path=hf_repo_id,
            mlx_path=upload_hf_repo_id,
            quantize=False)
```

```bash
❯ pip freeze
certifi==2024.2.2
charset-normalizer==3.3.2
filelock==3.14.0
fsspec==2024.3.1
huggingface-hub==0.22.2
idna==3.7
Jinja2==3.1.3
MarkupSafe==2.1.5
mlx==0.12.0
mlx-lm==0.12.1
numpy==1.26.4
packaging==24.0
protobuf==5.26.1
PyYAML==6.0.1
regex==2024.4.28
requests==2.31.0
safetensors==0.4.3
tokenizers==0.19.1
tqdm==4.66.2
transformers==4.40.1
typing_extensions==4.11.0
urllib3==2.2.1
```

**Comment by awni** [comment]
This is a known issue with the OpenELM repos. I created a discussion in one of the HF repos on this to fix it: https://huggingface.co/apple/OpenELM-270M/discussions/2

In the meantime you can use the models in the MLX Community https://huggingface.co/collections/mlx-community/openelm-6632820e30fcf1ce9907793b.

Another option is to hack the tokenizer to point to a comapatible tokenizer:

Change [that line](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tokenizer_utils.py#L315) to something like:

```
tokenizer_file = Path("mlx-community/OpenELM-3B")
```

**Comment by awni** [comment]
Closing this as we won't add a fix in MLX LM. But will try to get the original OpenLM models to be compatible with transformers instead.
