### ISSUE TITLE
Llama-3-8B-Instruct-Gradient-1048k-4bit not working?

### ISSUE THREAD

**Issue by katopz** [ml-explore/mlx-examples#754]
Try
```bash
python3 -m venv .venv
source .venv/bin/activate
pip install -U mlx-lm --quiet

# MODEL=mlx-community/Llama-3-8B-Instruct-Gradient-1048k-8bit
MODEL=mlx-community/Llama-3-8B-Instruct-Gradient-1048k-4bit

python3 -m mlx_lm.generate --model ${MODEL} --prompt "Write helloworld code in Rust"
```

Got
```
special_tokens_map.json: 100%|██████████████████| 301/301 [00:00<00:00, 609kB/s]
config.json: 100%|█████████████████████████████| 785/785 [00:00<00:00, 3.17MB/s]
model.safetensors.index.json: 100%|█████████| 52.4k/52.4k [00:00<00:00, 202kB/s]
tokenizer_config.json: 100%|████████████████| 51.0k/51.0k [00:00<00:00, 196kB/s]
tokenizer.json: 100%|██████████████████████| 9.09M/9.09M [00:02<00:00, 4.03MB/s]
model.safetensors: 100%|███████████████████| 4.52G/4.52G [03:32<00:00, 21.2MB/s]
Fetching 6 files: 100%|███████████████████████████| 6/6 [03:33<00:00, 35.60s/it]
Traceback (most recent call last):█████████| 4.52G/4.52G [03:32<00:00, 19.3MB/s]
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx_lm/generate.py", line 139, in <module>
    main(args)
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx_lm/generate.py", line 107, in main
    model, tokenizer = load(
                       ^^^^^
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx_lm/utils.py", line 385, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx_lm/utils.py", line 349, in load_model
    model.load_weights(list(weights.items()))
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 203, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.embed_tokens.biases model.embed_tokens.scales.
```

Other model seem working fine btw.

**Comment by awni** [comment]
Looks like you might be using an old mlx-lm.

Maybe try `python3 -m pip install -U mlx-lm`

And then check `python3 -c "import mlx_lm; print(mlx_lm.__version__)"` to make sure its `0.12.1`.

**Comment by katopz** [comment]
`0.12.1` working thanks
