### ISSUE TITLE
01-ai/Yi-1.5-9B-Chat got ValueError: Cannot instantiate this tokenizer from a slow version.

### ISSUE THREAD

**Issue by katopz** [ml-explore/mlx-examples#786]
run
```
python3 -m venv .venv                    
source .venv/bin/activate                                 
python3 -m pip install -U mlx-lm
python3 -c "import mlx_lm; print(mlx_lm.__version__)"

MODEL=01-ai/Yi-1.5-9B-Chat
python -m mlx_lm.generate --model ${MODEL} --prompt "write helloworld code in Rust"
```
got
```
0.13.0

You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx_lm/generate.py", line 159, in <module>
    main()
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx_lm/generate.py", line 125, in main
    model, tokenizer = load(
                       ^^^^^
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx_lm/utils.py", line 406, in load
    tokenizer = load_tokenizer(model_path, tokenizer_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/mlx_lm/tokenizer_utils.py", line 328, in load_tokenizer
    AutoTokenizer.from_pretrained(model_path, **tokenizer_config_extra),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 862, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 124, in __init__
    super().__init__(
  File "/Users/katopz/git/mlx-examples/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 102, in __init__
    raise ValueError(
ValueError: Cannot instantiate this tokenizer from a slow version. If it's based on sentencepiece, make sure you have sentencepiece installed.
```

Not sure we support [`01-ai/Yi-1.5-9B-Chat`](https://huggingface.co/01-ai/Yi-1.5-9B-Chat)?
![image](https://github.com/ml-explore/mlx-examples/assets/97060/e9b76501-915c-4d55-982b-08e7a3e410ce)

**Comment by katopz** [comment]
Still no joy, same error.
```
pip install sentencepiece
Requirement already satisfied: sentencepiece in ./.venv/lib/python3.12/site-packages (0.2.0)
```

**Comment by awni** [comment]
I just tried the model it works fine for me. So maybe make sure you are installing packages in the right env:

```
python -m pip install -U transformers
python -m pip install -U sentencepiece
```

There could be another package you need but hopefully that is all.

**Comment by katopz** [comment]
Working now! Thanks!
