### ISSUE TITLE
Error when running inference on newly converted OpenELM MLX model,  ValueError(f"Received parameters not in model: {extras}.")

### ISSUE THREAD

**Issue by Paramstr** [ml-explore/mlx-examples#819]
Similar to #742 

Converted successfully with no errors. When using the following command got errors mentioned at the bottom.

## Conversion Command
Note: Added line in tokenizer_utils.py (in def load_tokenizer)
    model_path = Path("meta-llama/Llama-2-7b-hf")

```
python3 -m mlx_lm.convert --hf-path Paramstr/OpenELM_1.1b_UiRev_finetuned_V2 -q
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[INFO] Loading
Fetching 6 files: 100%|
tokenizer_config.json: 100%|
tokenizer.model: 100%|
tokenizer.json: 100%|
special_tokens_map.json: 100%|
[INFO] Quantizing
```
## Inference Command
```
python3 -m mlx_lm.generate --max-tokens 1000 --temp 0.7 --model ./mlx_model --prompt "Tell me a story about Python programming"
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
```

## Error
```
 None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/USER/Downloads/Raw Downloads/mlx-examples-main-2/llms/mlx_lm/generate.py", line 161, in <module>
    main()
  File "/Users/USER/Downloads/Raw Downloads/mlx-examples-main-2/llms/mlx_lm/generate.py", line 125, in main
    model, tokenizer = load(
                       ^^^^^
  File "/Users/USER/Downloads/Raw Downloads/mlx-examples-main-2/llms/mlx_lm/utils.py", line 452, in load
    model = load_model(model_path, lazy, model_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Downloads/Raw Downloads/mlx-examples-main-2/llms/mlx_lm/utils.py", line 413, in load_model
    model.load_weights(list(weights.items()))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml_playground/lib/python3.12/site-packages/mlx/nn/layers/base.py", line 211, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: transformer.layers.10.ffn.proj_1.scales transformer.layers.26.ffn.proj_2.scales transformer.layers.0.ffn.proj_1.biases transformer.layers.5.attn.out_proj.biases transformer.layers.3.attn.qkv_proj.biases transformer.layers.6.attn.qkv_proj.scales transformer.layers.12.ffn.proj_1.biases transformer.layers.17.ffn.proj_2.biases transformer.layers.23.ffn.proj_2.biases transformer.layers.20.ffn.proj_2.biases transformer.layers.2.ffn.proj_2.scales transformer.layers.4.ffn.proj_1.scales transformer.layers.19.ffn.proj_2.biases transformer.layers.26.attn.out_proj.scales transformer.layers.13.attn.out_proj.scales transformer.layers.9.ffn.proj_2.biases transformer.layers.22.ffn.proj_1.biases transformer.layers.21.attn.qkv_proj.biases transformer.layers.21.ffn.proj_1.biases transformer.layers.24.attn.out_proj.scales transformer.layers.14.attn.qkv_proj.biases transformer.layers.1.attn.out_proj.biases transformer.layers.3.ffn.proj_2.scales transformer.layers.9.ffn.proj_1.biases transformer.layers.2.ffn.proj_2.biases transformer.layers.13.ffn.proj_2.scales transformer.layers.6.attn.qkv_proj.biases transformer.layers.11.ffn.proj_1.scales transformer.layers.16.ffn.proj_2.biases transformer.layers.23.ffn.proj_2.scales transformer.layers.14.ffn.proj_1.biases transformer.layers.7.ffn.proj_1.biases transformer.layers.23.attn.out_proj.scales transformer.layers.5.ffn.proj_1.biases transformer.layers.15.ffn.proj_2.biases transformer.layers.20.ffn.proj_1.scales transformer.layers.0.ffn.proj_2.biases transformer.layers.20.ffn.proj_1.biases transformer.layers.19.ffn.proj_2.scales transformer.layers.9.attn.qkv_proj.biases transformer.layers.20.attn.qkv_proj.scales transformer.layers.0.attn.qkv_proj.biases transformer.layers.23.ffn.proj_1.biases transformer.layers.8.ffn.proj_1.biases transformer.layers.24.ffn.proj_2.scales transformer.layers.24.attn.out_proj.biases transformer.layers.17.ffn.proj_2.scales transformer.layers.13.ffn.proj_2.biases transformer.layers.1.ffn.proj_1.scales transformer.layers.5.ffn.proj_2.scales transformer.layers.18.attn.qkv_proj.biases transformer.layers.17.attn.out_proj.biases transformer.layers.19.attn.out_proj.biases transformer.layers.26.ffn.proj_1.biases transformer.layers.27.attn.qkv_proj.biases transformer.layers.5.attn.qkv_proj.scales transformer.layers.27.ffn.proj_1.biases transformer.layers.23.attn.qkv_proj.scales transformer.layers.9.ffn.proj_2.scales transformer.layers.26.attn.out_proj.biases transformer.layers.7.attn.out_proj.scales transformer.layers.20.attn.qkv_proj.biases transformer.layers.22.attn.out_proj.scales transformer.layers.25.ffn.proj_2.biases transformer.layers.18.ffn.proj_2.scales transformer.layers.6.ffn.proj_2.scales transformer.layers.13.attn.qkv_proj.scales transformer.layers.8.ffn.proj_2.biases transformer.layers.19.attn.out_proj.scales transformer.layers.12.attn.out_proj.scales transformer.layers.21.attn.qkv_proj.scales transformer.layers.19.ffn.proj_1.biases transformer.layers.0.ffn.proj_2.scales transformer.layers.11.attn.out_proj.scales transformer.layers.25.ffn.proj_1.biases transformer.layers.3.ffn.proj_1.biases transformer.layers.26.ffn.proj_1.scales transformer.layers.22.ffn.proj_2.scales transformer.layers.2.attn.out_proj.biases transformer.layers.19.ffn.proj_1.scales transformer.layers.25.ffn.proj_2.scales transformer.layers.12.ffn.proj_2.biases transformer.layers.5.attn.qkv_proj.biases transformer.layers.2.ffn.proj_1.scales transformer.layers.12.ffn.proj_1.scales transformer.layers.8.attn.qkv_proj.biases transformer.layers.8.ffn.proj_2.scales transformer.layers.3.ffn.proj_2.biases transformer.layers.4.ffn.proj_1.biases transformer.layers.21.attn.out_proj.biases transformer.layers.20.attn.out_proj.biases transformer.layers.7.ffn.proj_1.scales transformer.token_embeddings.scales transformer.layers.25.attn.out_proj.biases transformer.layers.9.attn.out_proj.scales transformer.layers.1.attn.qkv_proj.biases transformer.layers.4.attn.out_proj.scales transformer.layers.4.attn.qkv_proj.scales transformer.layers.10.attn.qkv_proj.biases transformer.layers.19.attn.qkv_proj.biases transformer.layers.27.attn.out_proj.biases transformer.layers.24.ffn.proj_2.biases transformer.layers.17.attn.out_proj.scales transformer.layers.5.ffn.proj_1.scales transformer.layers.24.ffn.proj_1.biases transformer.layers.10.attn.out_proj.biases transformer.layers.14.ffn.proj_2.scales transformer.layers.18.attn.out_proj.scales transformer.layers.4.ffn.proj_2.biases transformer.layers.18.ffn.proj_2.biases transformer.layers.1.attn.out_proj.scales transformer.layers.2.attn.qkv_proj.scales transformer.layers.25.attn.qkv_proj.scales transformer.layers.1.attn.qkv_proj.scales transformer.layers.13.ffn.proj_1.biases transformer.layers.2.ffn.proj_1.biases transformer.layers.15.ffn.proj_1.biases transformer.layers.20.ffn.proj_2.scales transformer.layers.27.ffn.proj_2.biases transformer.layers.11.attn.qkv_proj.biases transformer.layers.11.ffn.proj_2.biases transformer.layers.7.ffn.proj_2.scales transformer.layers.1.ffn.proj_1.biases transformer.layers.22.ffn.proj_2.biases transformer.layers.17.attn.qkv_proj.biases transformer.layers.8.attn.qkv_proj.scales transformer.layers.8.attn.out_proj.scales transformer.layers.13.attn.qkv_proj.biases transformer.layers.10.ffn.proj_1.biases transformer.layers.27.ffn.proj_2.scales transformer.layers.9.attn.out_proj.biases transformer.layers.7.ffn.proj_2.biases transformer.layers.24.ffn.proj_1.scales transformer.layers.15.attn.out_proj.scales transformer.layers.27.attn.qkv_proj.scales transformer.layers.18.attn.qkv_proj.scales transformer.layers.21.ffn.proj_2.biases transformer.layers.1.ffn.proj_2.biases transformer.layers.19.attn.qkv_proj.scales transformer.layers.4.attn.qkv_proj.biases transformer.layers.15.attn.out_proj.biases transformer.layers.12.attn.qkv_proj.biases transformer.layers.6.ffn.proj_1.biases transformer.layers.18.ffn.proj_1.scales transformer.layers.8.ffn.proj_1.scales transformer.layers.14.ffn.proj_1.scales transformer.layers.6.ffn.proj_1.scales transformer.layers.22.attn.out_proj.biases transformer.layers.25.attn.qkv_proj.biases transformer.layers.3.attn.out_proj.biases transformer.layers.26.attn.qkv_proj.biases transformer.layers.11.attn.qkv_proj.scales transformer.layers.12.attn.out_proj.biases transformer.layers.9.attn.qkv_proj.scales transformer.layers.16.ffn.proj_1.scales transformer.layers.11.attn.out_proj.biases transformer.layers.0.ffn.proj_1.scales transformer.layers.10.attn.qkv_proj.scales transformer.layers.12.attn.qkv_proj.scales transformer.layers.25.attn.out_proj.scales transformer.layers.15.attn.qkv_proj.biases transformer.layers.3.ffn.proj_1.scales transformer.layers.11.ffn.proj_1.biases transformer.layers.6.ffn.proj_2.biases transformer.layers.14.attn.qkv_proj.scales transformer.layers.4.attn.out_proj.biases transformer.layers.5.attn.out_proj.scales transformer.layers.16.attn.qkv_proj.scales transformer.layers.15.ffn.proj_2.scales transformer.layers.11.ffn.proj_2.scales transformer.layers.27.ffn.proj_1.scales transformer.layers.18.attn.out_proj.biases transformer.layers.22.ffn.proj_1.scales transformer.layers.3.attn.out_proj.scales transformer.layers.1.ffn.proj_2.scales transformer.layers.6.attn.out_proj.biases transformer.layers.6.attn.out_proj.scales transformer.layers.16.attn.qkv_proj.biases transformer.layers.13.attn.out_proj.biases transformer.layers.0.attn.qkv_proj.scales transformer.layers.24.attn.qkv_proj.scales transformer.layers.17.ffn.proj_1.biases transformer.layers.3.attn.qkv_proj.scales transformer.layers.20.attn.out_proj.scales transformer.layers.4.ffn.proj_2.scales transformer.layers.22.attn.qkv_proj.scales transformer.layers.7.attn.qkv_proj.biases transformer.layers.17.ffn.proj_1.scales transformer.layers.21.ffn.proj_2.scales transformer.layers.18.ffn.proj_1.biases transformer.layers.7.attn.qkv_proj.scales transformer.layers.16.attn.out_proj.scales transformer.layers.24.attn.qkv_proj.biases transformer.layers.10.ffn.proj_2.biases transformer.layers.22.attn.qkv_proj.biases transformer.layers.21.ffn.proj_1.scales transformer.layers.16.attn.out_proj.biases transformer.layers.8.attn.out_proj.biases transformer.layers.14.attn.out_proj.scales transformer.layers.13.ffn.proj_1.scales transformer.layers.14.ffn.proj_2.biases transformer.layers.2.attn.out_proj.scales transformer.layers.10.attn.out_proj.scales transformer.layers.15.ffn.proj_1.scales transformer.layers.23.ffn.proj_1.scales transformer.layers.26.attn.qkv_proj.scales transformer.layers.12.ffn.proj_2.scales transformer.layers.14.attn.out_proj.biases transformer.layers.16.ffn.proj_1.biases transformer.token_embeddings.biases transformer.layers.21.attn.out_proj.scales transformer.layers.2.attn.qkv_proj.biases transformer.layers.0.attn.out_proj.biases transformer.layers.5.ffn.proj_2.biases transformer.layers.15.attn.qkv_proj.scales transformer.layers.23.attn.out_proj.biases transformer.layers.23.attn.qkv_proj.biases transformer.layers.0.attn.out_proj.scales transformer.layers.7.attn.out_proj.biases transformer.layers.25.ffn.proj_1.scales transformer.layers.10.ffn.proj_2.scales transformer.layers.17.attn.qkv_proj.scales transformer.layers.27.attn.out_proj.scales transformer.layers.16.ffn.proj_2.scales transformer.layers.26.ffn.proj_2.biases transformer.layers.9.ffn.proj_1.scales.
```

**Comment by Paramstr** [comment]
Update: During conversion, edited utils.py at line 688 to point to local tokenizer and now inference works. 
```
  tokenizer.save_pretrained("/Users/USER/Downloads/Raw Downloads/mlx-examples-main-2/llms/mlx_lm/Llama-2-7b-hf")
  ```
  
 However, using the model through LLMEvaluator gives the following error.
 libc++abi: terminating due to uncaught exception of type std::invalid_argument: [matmul] Last dimension of first input with shape (1,916,2048) must match second to last dimension of second input with shape (256,32000)
  
```
let modelConfiguration = ModelConfiguration(
id: "Paramstr/MLX_OpenELM_1.1b_UiRev_finetuned_V3",
overrideTokenizer: "meta-llama/Llama-2-7b-hf"
)
```
