### ISSUE TITLE
NameError: name 'resume_adapter_file' is not defined

### ISSUE THREAD

**Issue by rainrain1230** [ml-explore/mlx-examples#850]
I'm trying to resume fine-tuning following the instruction in [LORA.md](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md#Generate). It mentions that I can resume fine-tuning with an existing adapter with `--resume-adapter-file <path_to_adapters.safetensors>`. 

The script I used was:
```
mlx_lm.lora \
    --model Qwen/Qwen1.5-32B-Chat \
    --train \
    --data ./dataset/ \
    --iters 600 \
    --resume-adapter-file ./adapters/0000600_adapters.safetensors
```

However, following this method would lead to this error:
```
Traceback (most recent call last):
  File "/Users/rainchong/Library/Python/3.9/bin/mlx_lm.lora", line 8, in <module>
    sys.exit(main())
  File "/Users/rainchong/Library/Python/3.9/lib/python/site-packages/mlx_lm/lora.py", line 274, in main
    run(types.SimpleNamespace(**args))
  File "/Users/rainchong/Library/Python/3.9/lib/python/site-packages/mlx_lm/lora.py", line 247, in run
    train_model(args, model, tokenizer, train_set, valid_set, training_callback)
  File "/Users/rainchong/Library/Python/3.9/lib/python/site-packages/mlx_lm/lora.py", line 173, in train_model
    print(f"Loading pretrained adapters from {resume_adapter_file}")
NameError: name 'resume_adapter_file' is not defined
```

Any insight on this? Thanks!

**Comment by rainrain1230** [comment]
can be solved by making following change on mlx_lm/lora.py:173
```
print(f"Loading pretrained adapters from {resume_adapter_file}")
```
to
```
print(f"Loading pretrained adapters from {args.resume_adapter_file}")
```
