### ISSUE TITLE
Received parameters not in model: {extras}.

### ISSUE THREAD

**Issue by Gloriashield** [ml-explore/mlx-examples#854]
Good to see you. I'm a newbie. 

I am using an Apple M2 laptop. I am going to try to train a model using lora.py.  If I run the following.

```bash
python lora.py --train --model Qwen/Qwen2-0.5B-Instruct  --data /opt/mlx/data --batch-size 2 --lora-layers 8 
```

I get the following error:
```
[INFO] Quantizing
Traceback (most recent call last):
  File "/opt/mlx/mlx-examples/lora/convert.py", line 93, in <module>
    weights, config = quantize(weights, config, args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/mlx/mlx-examples/lora/convert.py", line 18, in quantize
    model.load_weights(list(weights.items()))
  File "/Users/kasumi/.mlx/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 211, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
```

Using a different model does not resolve this issue. Please help me :D

- Sonoma 14.5
- Python 3.11.6

Thank you!

**Comment by awni** [comment]
The `lora.py` example only supports a limited set of models. To run with more models use MLX LM.

1. `pip install -U mlx-lm`
2. `mlx_lm.lora --train --model Qwen/Qwen2-0.5B-Instruct  --data /opt/mlx/data --batch-size 2 --lora-layers 8`

More [documentation here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/LORA.md). If that doesn't solve the problem, let us know and I can re-open this issue.
