### ISSUE TITLE
mlx_lm.fuse raises RuntimeError: std::bad_cast

### ISSUE THREAD

**Issue by eltbus** [ml-explore/mlx-examples#927]
Version: `mlx-lm = "^0.16.1"`

# Context:
I successfully ran `python -m mlx_lm.lora` to train the model:
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Loading pretrained model
Fetching 12 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 111353.20it/s]
Loading datasets
Training
Trainable parameters: 0.012% (0.852M/7248.024M)
Starting training..., iters: 10
Iter 1: Val loss 2.483, Val took 39.601s
Iter 10: Val loss 2.217, Val took 37.661s
Iter 10: Train loss 2.408, Learning Rate 1.000e-05, It/sec 6.188, Tokens/sec 1256.793, Trained Tokens 2031, Peak mem 14.318 GB
Saved final adapter weights to adapters/adapters.safetensors.
```

# Issue
I am running into the following error when trying to generate the local GGUF file:
```
python -m mlx_lm.fuse \
    --model mistralai/Mistral-7B-Instruct-v0.3 \
    --export-gguf
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Loading pretrained model
Fetching 12 files: 100%|████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 139422.85it/s]
Converting to GGUF format
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<my-path>/virtualenvs/mlx-examples-4Z3Ig8fK-py3.12/lib/python3.12/site-packages/mlx_lm/fuse.py", line 131, in <module>
    main()
  File "<my-path>/virtualenvs/mlx-examples-4Z3Ig8fK-py3.12/lib/python3.12/site-packages/mlx_lm/fuse.py", line 117, in main
    convert_to_gguf(model_path, weights, config, str(save_path / args.gguf_path))
  File "<my-path>/virtualenvs/mlx-examples-4Z3Ig8fK-py3.12/lib/python3.12/site-packages/mlx_lm/gguf.py", line 312, in convert_to_gguf
    mx.save_gguf(output_file_path, weights, metadata)
RuntimeError: std::bad_cast
```

Any idea regarding what could be wrong?

**Comment by awni** [comment]
I added a fix to #923
