### ISSUE TITLE
CLIP: preprocess

### ISSUE THREAD

**Issue by SauravMaheshkar** [ml-explore/mlx-examples#959]
Hi 👋🏽 I wanted to replicate the [Linear-probe evaluation script from the official CLIP repository](https://github.com/openai/CLIP?tab=readme-ov-file#linear-probe-evaluation). However, I can't figure out how to properly pre-process the images. I've attached my script and the corresponding error trace.

<details>

<summary>Evaluation script</summary>

```python
import numpy as np
import mlx.core as mx
from mlx.data.datasets import load_cifar10

from model import CLIPModel
from image_processor import CLIPImageProcessor


def get_cifar10(batch_size, root=None):
    mean = np.array([0.485, 0.456, 0.406]).reshape((1, 1, 3))
    std = np.array([0.229, 0.224, 0.225]).reshape((1, 1, 3))

    def normalize(x):
        x = x.astype(np.float32) / 255.0
        return (x - mean) / std

    tr = load_cifar10(root=root)
    tr_iter = tr.to_stream().key_transform("image", normalize).batch(batch_size)

    test = load_cifar10(root=root, train=False)
    test_iter = test.to_stream().key_transform("image", normalize).batch(batch_size)

    return tr_iter, test_iter


def get_features(model, iter):
    all_features = []
    all_labels = []
    image_proc = CLIPImageProcessor.from_pretrained("mlx_model")

    for _, batch in enumerate(iter):
        image, label = batch["image"], batch["label"]
        x = image_proc([mx.array(image)])
        y = mx.array(label)

        image_embeds = model.get_image_features(x)
        all_features.append(image_embeds)
        all_labels.append(y)

    return mx.concatenate(all_features), mx.concatenate(all_labels)


if __name__ == "__main__":
    model = CLIPModel.from_pretrained("mlx_model")

    train_iter, test_iter = get_cifar10(batch_size=256)
    train_features, train_labels = get_features(model, train_iter)
    test_features, test_labels = get_features(model, test_iter)
```

</details>

<details>
<summary>Error</summary>

```console
Traceback (most recent call last):
  File "/Users/saurav/dev/SauravMaheshkar/mlx-examples/clip/eval.py", line 47, in <module>
    train_features, train_labels = get_features(model, train_iter)
  File "/Users/saurav/dev/SauravMaheshkar/mlx-examples/clip/eval.py", line 33, in get_features
    x = image_proc([mx.array(image)])
  File "/Users/saurav/dev/SauravMaheshkar/mlx-examples/clip/image_processor.py", line 39, in __call__
    [self._preprocess(image)[None] for image in images], axis=0
  File "/Users/saurav/dev/SauravMaheshkar/mlx-examples/clip/image_processor.py", line 39, in <listcomp>
    [self._preprocess(image)[None] for image in images], axis=0
  File "/Users/saurav/dev/SauravMaheshkar/mlx-examples/clip/image_processor.py", line 44, in _preprocess
    image = resize(image, self.size)
  File "/Users/saurav/dev/SauravMaheshkar/mlx-examples/clip/image_processor.py", line 65, in resize
    width, height = image.size
TypeError: cannot unpack non-iterable int object
```

</details>

**Comment by awni** [comment]
The resize function in our Clip example takes a PIL `Image` not an `mx.array`.

I would remove the CIFAR-10 preprocessing and just load the byte arrays directly into a PIL.Image using `Image.fromarray`. From there you should be able to use the image preprocessing for the CLIP model.

So concretely change the dataset loading to:

```python
def get_cifar10(batch_size, root=None):
    tr = load_cifar10(root=root)
    tr_iter = tr.to_stream().batch(batch_size)

    test = load_cifar10(root=root, train=False)
    test_iter = test.to_stream().batch(batch_size)

    return tr_iter, test_iter
```

And modify the loop like so:

```python
        x = image_proc([Image.fromarray(im) for im in image])
```

Make sure to add `from PIL import Image`.
