### ISSUE TITLE
huggingface_hub 0.25 causes error upon importing from mlx_lm

### ISSUE THREAD

**Issue by arogister** [ml-explore/mlx-examples#988]
I have noticed this error upon importing from mlx_lm. I have found out that it seems due to a breaking change in huggingface_hub 0.25, which was released today. I reverted to HF_hub version 0.24.6 and this fixes the problem.

Python 3.12.6 (main, Sep  9 2024, 21:36:32) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mlx_lm import load, generate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arogister/Documents/mlx/.venv/lib/python3.12/site-packages/mlx_lm/__init__.py", line 3, in <module>
    from .utils import convert, generate, load, stream_generate
  File "/Users/arogister/Documents/mlx/.venv/lib/python3.12/site-packages/mlx_lm/utils.py", line 17, in <module>
    from huggingface_hub.utils._errors import RepositoryNotFoundError
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'

**Comment by awni** [comment]
Well I guess it's a private variable so we probably shouldn't be using that.
