### ISSUE TITLE
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'

### ISSUE THREAD

**Issue by ndurner** [ml-explore/mlx-examples#994]
# Error
With newest mlx-lm (0.18.1-py3):
```
% mlx_lm.generate --version        
Traceback (most recent call last):
  File "/private/tmp/tt/bin/mlx_lm.generate", line 5, in <module>
    from mlx_lm.generate import main
  File "/private/tmp/tt/lib/python3.12/site-packages/mlx_lm/__init__.py", line 3, in <module>
    from .utils import convert, generate, load, stream_generate
  File "/private/tmp/tt/lib/python3.12/site-packages/mlx_lm/utils.py", line 17, in <module>
    from huggingface_hub.utils._errors import RepositoryNotFoundError
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'
```

# Installation procedure
(per https://github.com/ml-explore/mlx-examples/tree/main/llms#generate-text-with-llms-and-mlx)
```
% /usr/local/bin/python3 -m venv tt
% source tt/bin/activate

% pip install -U mlx-lm
Collecting mlx-lm
  Using cached mlx_lm-0.18.1-py3-none-any.whl.metadata (6.9 kB)
Collecting mlx>=0.17.0 (from mlx-lm)
  Using cached mlx-0.17.3-cp312-cp312-macosx_14_0_arm64.whl.metadata (5.1 kB)
Collecting numpy (from mlx-lm)
  Using cached numpy-2.1.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting transformers>=4.39.3 (from transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached transformers-4.44.2-py3-none-any.whl.metadata (43 kB)
Collecting protobuf (from mlx-lm)
  Using cached protobuf-5.28.1-cp38-abi3-macosx_10_9_universal2.whl.metadata (592 bytes)
Collecting pyyaml (from mlx-lm)
  Using cached PyYAML-6.0.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting jinja2 (from mlx-lm)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock (from transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached huggingface_hub-0.25.0-py3-none-any.whl.metadata (13 kB)
Collecting packaging>=20.0 (from transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting regex!=2019.12.17 (from transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached regex-2024.9.11-cp312-cp312-macosx_11_0_arm64.whl.metadata (40 kB)
Collecting requests (from transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting safetensors>=0.4.1 (from transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached safetensors-0.4.5-cp312-cp312-macosx_11_0_arm64.whl.metadata (3.8 kB)
Collecting tokenizers<0.20,>=0.19 (from transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached tokenizers-0.19.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.7 kB)
Collecting tqdm>=4.27 (from transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
Collecting sentencepiece!=0.1.92,>=0.1.91 (from transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached sentencepiece-0.2.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (7.7 kB)
Collecting MarkupSafe>=2.0 (from jinja2->mlx-lm)
  Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl.metadata (3.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.23.2->transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub<1.0,>=0.23.2->transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests->transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->transformers>=4.39.3->transformers[sentencepiece]>=4.39.3->mlx-lm)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Using cached mlx_lm-0.18.1-py3-none-any.whl (109 kB)
Using cached mlx-0.17.3-cp312-cp312-macosx_14_0_arm64.whl (21.5 MB)
Using cached transformers-4.44.2-py3-none-any.whl (9.5 MB)
Using cached numpy-2.1.1-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
Using cached PyYAML-6.0.2-cp312-cp312-macosx_11_0_arm64.whl (173 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached protobuf-5.28.1-cp38-abi3-macosx_10_9_universal2.whl (414 kB)
Using cached huggingface_hub-0.25.0-py3-none-any.whl (436 kB)
Using cached MarkupSafe-2.1.5-cp312-cp312-macosx_10_9_universal2.whl (18 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached regex-2024.9.11-cp312-cp312-macosx_11_0_arm64.whl (284 kB)
Using cached safetensors-0.4.5-cp312-cp312-macosx_11_0_arm64.whl (381 kB)
Using cached sentencepiece-0.2.0-cp312-cp312-macosx_11_0_arm64.whl (1.2 MB)
Using cached tokenizers-0.19.1-cp312-cp312-macosx_11_0_arm64.whl (2.4 MB)
Using cached tqdm-4.66.5-py3-none-any.whl (78 kB)
Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.3.2-cp312-cp312-macosx_11_0_arm64.whl (119 kB)
Using cached fsspec-2024.9.0-py3-none-any.whl (179 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: sentencepiece, urllib3, typing-extensions, tqdm, safetensors, regex, pyyaml, protobuf, packaging, numpy, mlx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, huggingface-hub, tokenizers, transformers, mlx-lm
Successfully installed MarkupSafe-2.1.5 certifi-2024.8.30 charset-normalizer-3.3.2 filelock-3.16.1 fsspec-2024.9.0 huggingface-hub-0.25.0 idna-3.10 jinja2-3.1.4 mlx-0.17.3 mlx-lm-0.18.1 numpy-2.1.1 packaging-24.1 protobuf-5.28.1 pyyaml-6.0.2 regex-2024.9.11 requests-2.32.3 safetensors-0.4.5 sentencepiece-0.2.0 tokenizers-0.19.1 tqdm-4.66.5 transformers-4.44.2 typing-extensions-4.12.2 urllib3-2.2.3

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

% mlx_lm.generate --version        
Traceback (most recent call last):
  File "/private/tmp/tt/bin/mlx_lm.generate", line 5, in <module>
    from mlx_lm.generate import main
  File "/private/tmp/tt/lib/python3.12/site-packages/mlx_lm/__init__.py", line 3, in <module>
    from .utils import convert, generate, load, stream_generate
  File "/private/tmp/tt/lib/python3.12/site-packages/mlx_lm/utils.py", line 17, in <module>
    from huggingface_hub.utils._errors import RepositoryNotFoundError
ModuleNotFoundError: No module named 'huggingface_hub.utils._errors'
```

**Comment by lherron** [comment]
Same.  Downgrading to huggingface-hub==0.24.7 fixed it.

**Comment by awni** [comment]
FYI this is fixed in main we just need to do a release.

**Comment by awni** [comment]
This should be fixed if you do `pip install -U mlx-lm`
