### ISSUE TITLE
“tokenizer.ggml.unknown_token_id” is it definitly required?

### ISSUE THREAD

**Issue by fynv** [ml-explore/mlx-examples#999]
Hi, I'm quite new to this. 
Trying to run Llama-3.2-3B-Instruct-Q8_0-GGUF using the gguf file:

```
% python generate.py --repo hugging-quants/Llama-3.2-3B-Instruct-Q8_0-GGUF --gguf /Users/fei/LargeModels/llama-3.2-3b-instruct-q8_0.gguf --prompt "Write a quicksort in Python"
[INFO] Loading model from /Users/fei/LargeModels/llama-3.2-3b-instruct-q8_0.gguf
8 bits quantized model
Model info
==========
Context length: 131072
Vocab size: 128256
Hidden size: 3072
Num layers: 28
Num attention heads: 24

dict_keys(['tokenizer.chat_template', 'tokenizer.ggml.eos_token_id', 'tokenizer.ggml.merges', 'tokenizer.ggml.token_type', 'tokenizer.ggml.tokens', 'tokenizer.ggml.model', 'llama.embedding_length', 'llama.vocab_size', 'tokenizer.ggml.pre', 'llama.attention.value_length', 'llama.attention.head_count', 'llama.attention.key_length', 'llama.attention.head_count_kv', 'general.basename', 'general.tags', 'general.size_label', 'llama.block_count', 'general.languages', 'llama.context_length', 'general.file_type', 'general.finetune', 'llama.feed_forward_length', 'llama.attention.layer_norm_rms_epsilon', 'general.architecture', 'general.quantization_version', 'llama.rope.dimension_count', 'llama.rope.freq_base', 'tokenizer.ggml.bos_token_id', 'general.type', 'general.name'])
Traceback (most recent call last):
  File "/Users/fei/mlx-examples/llms/gguf_llm/generate.py", line 85, in <module>
    model, tokenizer = models.load(args.gguf, args.repo)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fei/mlx-examples/llms/gguf_llm/models.py", line 308, in load
    tokenizer = GGUFTokenizer(metadata)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fei/mlx-examples/llms/gguf_llm/models.py", line 227, in __init__
    self._tokenizer = utils.spm_tokenizer(metadata)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fei/mlx-examples/llms/gguf_llm/utils.py", line 10, in spm_tokenizer
    unk = metadata["tokenizer.ggml.unknown_token_id"].item()
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'tokenizer.ggml.unknown_token_id'

```

(The dict_keys output is because I added a print add the beginning of spm_tokenizer())

**Comment by awni** [comment]
If want to run that model with MLX your best bet is to use MLX LM which uses safetensors:

First `pip install mlx-lm`, then:

```
mlx_lm.generate --model mlx-community/Llama-3.2-3B-Instruct-4bit --prompt "Write a story about Einstein" --temp 0.0 --max-tokens 512
```

**Comment by fynv** [comment]
> If want to run that model with MLX your best bet is to use MLX LM which uses safetensors:
> 
> First `pip install mlx-lm`, then:
> 
> ```
> mlx_lm.generate --model mlx-community/Llama-3.2-3B-Instruct-4bit --prompt "Write a story about Einstein" --temp 0.0 --max-tokens 512
> ```

Thanks, it works!
